import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

const routesDir = path.join(__dirname, 'routes');
const files = fs.readdirSync(routesDir).filter(f => f.endsWith('.js') && f !== 'index.js');

let output = '# 🚀 Full LMS Platform API Documentation \n\n';
output += '> **Base URL:** `http://localhost:8000` (Update to your live API domain)\n\n';
output += 'Autogenerated summary of all available routes, complete with functional explanations and cURL templates.\n\n---\n\n';

files.forEach(file => {
    const routePrefix = file.replace(/Routes?\.js|Router\.js|routes?\.js|\.js/i, '').toLowerCase();
    const apiPrefix = `/api/${routePrefix === 'user' ? 'user' : routePrefix}`;

    let content = fs.readFileSync(path.join(routesDir, file), 'utf8');
    const routeRegex = /(?:router|.*Router|app)\.(get|post|put|delete|patch)\(\s*['"]([^'"]+)['"]/g;

    let match;
    let endpointCount = 0;
    const endpointsBuffer = [];

    while ((match = routeRegex.exec(content)) !== null) {
        endpointCount++;
        const method = match[1].toUpperCase();
        let endpoint = match[2];

        let pathStr = `${apiPrefix}${endpoint.replace(/\/$/, '')}`;
        if (endpoint === '/') pathStr = `${apiPrefix}`;
        pathStr = pathStr.replace(/\/\//g, '/');

        endpointsBuffer.push(`### ${method} \`${pathStr}\``);

        // --- ADD EXPLANATION LOGIC ---
        let description = "Performs an operation on this resource.";

        if (method === 'GET') {
            if (endpoint.includes('/:id') || endpoint.includes('/:slug') || endpoint.includes('details')) {
                description = "Retrieves deep details for a specific individual record by its unique identifier (ID or slug). Returns a rich data object.";
            } else if (endpoint.includes('my-')) {
                description = "Fetches a personalized list of records specifically belonging to the currently authenticated user.";
            } else if (endpoint.includes('stats') || endpoint.includes('report') || endpoint.includes('analytics')) {
                description = "Aggregates and retrieves analytical data, statistical reporting, or high-level summaries.";
            } else if (endpoint.includes('search') || endpoint.includes('filter')) {
                description = "Queries the database for a collection of records matching specific query filters.";
            } else {
                description = "Retrieves a listing or collection of records. Often supports query parameters for filtering/pagination (e.g. `?page=1&limit=20`).";
            }
        } else if (method === 'POST') {
            if (endpoint.includes('upload') || endpoint.includes('image') || endpoint.includes('video')) {
                description = "Uploads media or attachment files to the server, processing multipart/form-data, returning an accessible URL.";
            } else if (endpoint.includes('login') || endpoint.includes('auth') || endpoint.includes('token')) {
                description = "Authenticates user credentials and provisions new JWT session access and refresh tokens.";
            } else {
                description = "Creates a new resource entry in the database or performs a distinct state-changing action (like a checkout or import). Requires a JSON payload.";
            }
        } else if (method === 'PUT' || method === 'PATCH') {
            description = "Updates an existing database record. Provide a JSON payload containing the fields you wish to modify. Other fields remain untouched.";
        } else if (method === 'DELETE') {
            description = "Irreversibly deletes or permanently deactivates (soft deletes) a specified resource in the database.";
        }

        endpointsBuffer.push(`**Description:** ${description}  `);

        // Indicate Authorization needs based on standard middleware presence
        const chunk = content.substring(match.index - 50, match.index + 200);
        let authLevel = "None (Public API)";
        if (chunk.includes('isAdmin')) {
            authLevel = "Admin / Instructor Required (JWT)";
        } else if (chunk.includes('passport.authenticate') || chunk.includes('accessTokenAutoRefresh')) {
            authLevel = "Authenticated User (JWT)";
        }
        endpointsBuffer.push(`**Auth Required:** ${authLevel}  `);

        // Write simple curl payload
        endpointsBuffer.push('\n```bash');
        let curlCommand = `curl -X ${method} "http://localhost:8000${pathStr}" \\\n  -H "Accept: application/json"`;

        if (authLevel !== "None (Public API)") {
            curlCommand += ` \\\n  -H "Authorization: Bearer <ACCESS_TOKEN>"`;
        }

        if (method === 'POST' || method === 'PUT' || method === 'PATCH') {
            curlCommand += ` \\\n  -H "Content-Type: application/json" \\\n  -d '{}'`;
        }

        endpointsBuffer.push(curlCommand);
        endpointsBuffer.push('```\n');
    }

    if (endpointCount > 0) {
        output += `## 🗂️ Module: ${routePrefix.toUpperCase()}\n`;
        output += Object.entries(endpointsBuffer).map(e => e[1]).join('\n') + '---\n\n';
    }
});

const outputPath = path.join(__dirname, 'full_lms_api_documentation_curl.md');
fs.writeFileSync(outputPath, output);
console.log('Docs with explanations generated successfully!');
