import React, { createContext, useContext, useState, useEffect } from 'react'

const translations = {
  en: {
    // Navigation & General
    home: 'Home',
    ourCourses: 'Our Courses',
    forum: 'Forum',
    gig: 'Gig',
    news: 'News',
    dashboard: 'Dashboard',
    signIn: 'Sign In',
    logOut: 'Log Out',
    liveClasses: 'Live Classes',
    profile: 'Profile',
    myActivity: 'My Activity',
    myForum: 'My Forum',
    mySubmissions: 'My Submissions',
    myPurchases: 'My Purchases',
    myCourses: 'My Courses',
    allCourses: 'All Courses',
    jobPostings: 'Job Postings',
    support: 'Support & Help',

    // Profile & User Info
    security: 'Security',
    academic: 'Academic',
    profileDetails: 'Profile Details',
    fullNameLabel: 'Full Name',
    emailAddressLabel: 'Email Address',
    phoneNumberLabel: 'Phone Number',
    locationLabel: 'Location',
    aboutMeBio: 'About Me / Bio',
    companyNameLabel: 'Company Name',
    gstNumberLabel: 'GST Number',
    saveChangesBtn: 'Save Changes',
    savingState: 'Saving...',
    changesSavedMsg: 'Changes Saved',
    currentPasswordLabel: 'Current Password',
    newPasswordLabel: 'New Password',
    confirmPasswordLabel: 'Confirm Password',
    updatePasswordBtn: 'Update Password',
    cancelBtn: 'Cancel',
    studentRole: 'Student',
    memberRole: 'Member',
    coursesStat: 'Courses',
    postsStat: 'Posts',
    certificatesStat: 'Certificates',
    personalityArchetype: 'Personality Archetype',
    coreDescription: 'Core Description',
    bioSummary: 'Bio Summary',
    noBioRecorded: 'No bio recorded in the registry.',
    badgesTitle: 'Badges',
    earlyAdopter: 'Early Adopter',
    verifiedUser: 'Verified User',
    accountInfo: 'Account Info',
    lockedLabel: 'Locked',

    // Live Classes
    liveSignal: 'LIVE SIGNAL',
    noClassesActive: 'No classes currently active.',
    meetingDisconnected: 'Meeting Disconnected',
    disconnectedDesc: 'You have left or been disconnected from this session.',
    reconnecting: 'RECONNECTING...',
    rejoin: 'REJOIN',
    dismiss: 'DISMISS',
    secureBroadcast: 'SECURE BROADCAST',
    allScheduledClasses: 'All Scheduled Classes',

    // Academic & Education
    educationHistory: 'Education History',
    viewAll: 'VIEW ALL',
    noHistoryRecorded: 'No History Recorded',
    addEducationDetails: 'Add your education details',
    addEducation: 'ADD EDUCATION',
    myDocuments: 'My Documents',
    uploadFile: 'UPLOAD FILE',

    // My Forum / Discourse
    myDiscourse: 'My Discourse',
    discourseSub: 'Archive of your community contributions and topics',
    totalThreads: 'TOTAL THREADS',
    engagement: 'ENGAGEMENT',
    calibrations: 'CALIBRATIONS',
    noContributionsFound: 'No contributions found',
    noThreadsStarted: "You haven't started any forum threads yet",

    // Submissions
    assignmentArchive: 'Assignment Archive',
    submissionsSub: 'Track your tactical submissions and performance metrics',
    performance: 'PERFORMANCE',

    // Purchases & Ledger
    archiveLedger: 'ARCHIVE & LEDGER',
    purchasesLedgerSub: 'Persistent record of intellectual acquisitions and institutional investments across the Edrilla network.',
    moduleArchive: 'MODULE ARCHIVE',
    acquisition: 'ACQUISITION',
    amount: 'AMOUNT',
    actions: 'ACTIONS',
    receipt: 'RECEIPT',
    refund: 'REFUND',

    // Messages
    messagesTitle: 'Messages',
    activeChats: 'Active chats:',
    chatsTab: 'CHATS',
    groupsTab: 'GROUPS',
    searchMessages: 'Search messages...',
    allFilter: 'ALL',
    unreadFilter: 'UNREAD',
    loadingChats: 'Loading chats...',
    connectionError: 'Connection Error',
    retryBtn: 'RETRY',
    reconnectBtn: 'RECONNECT',
    noMessagesFound: 'No messages found',
    participants: 'PARTICIPANTS',
    searchParticipants: 'Search participants...',
    clearChat: 'CLEAR CHAT',
    selectConversation: 'Select a conversation to start messaging',
    messagesSecure: 'Your messages are secure',
    typeMessage: 'Type a message...',

    // My Courses / Curriculum
    continuingEducation: 'CONTINUING EDUCATION',
    myCurriculum: 'MY CURRICULUM',
    activeCoursesLabel: 'ACTIVE COURSES',
    completionRateLabel: 'COMPLETION RATE',
    searchBtn: 'SEARCH',

    // All Courses Catalog
    curatedCatalog: 'CURATED CATALOG',
    ourCoursesTitle: 'OUR COURSES',
    availableStat: 'AVAILABLE',
    newTodayStat: 'NEW TODAY',
    allCoursesTab: 'ALL COURSES',
    businessTab: 'BUSINESS',
    digitalMarketingTab: 'DIGITAL MARKETING',
    showingCoursesLabel: 'SHOWING COURSES',
    advancedFiltersBtn: 'ADVANCED FILTERS',

    // Forum
    totalTopicsLabel: 'TOTAL TOPICS',
    activeUsersLabel: 'ACTIVE USERS',
    thisWeekLabel: 'THIS WEEK',
    recentDiscourse: 'RECENT DISCOURSE',
    filterByIntelligence: 'FILTER BY INTELLIGENCE',

    // Job Posts
    manageJobOpps: 'MANAGE AND TRACK YOUR PUBLISHED JOB OPPORTUNITIES',
    createNewPost: 'CREATE NEW POST',
    totalPostsLabel: 'TOTAL POSTS',
    activeLeadsLabel: 'ACTIVE LEADS',
    totalProposalsLabel: 'TOTAL PROPOSALS',
    myPublications: 'MY PUBLICATIONS',

    // Floating Navbar Popups
    recentDispatches: 'RECENT DISPATCHES',
    markAllRead: 'MARK ALL READ',
    viewAllAlerts: 'VIEW ALL ALERTS',
    protocolXPAcquired: 'Protocol XP Acquired',
    xpDesc: '+250 for Color Theory Basic',
    moduleUploaded: 'Module Uploaded',
    moduleUploadedDesc: 'New content in Cinematography',
    communitySignal: 'Community Signal',
    communitySignalDesc: 'Marcus R. replied to your thread',
    rankCarrier: 'RANK CARRIER',
    identityProfile: 'IDENTITY PROFILE',
    systemSettings: 'SYSTEM SETTINGS',
    accessKeys: 'ACCESS KEYS',

    // Support Screen
    supportCenter: 'SUPPORT CENTER',
    activeDispatches: 'ACTIVE DISPATCHES',
    raiseTicket: 'RAISE A TICKET',
    myTickets: 'MY TICKETS',
    contactInfo: 'CONTACT INFORMATION',
    supportCategory: 'SUPPORT CATEGORY',
    intelligenceBriefing: 'INTELLIGENCE BRIEFING',
    attachments: 'ATTACHMENTS',
    submitDispatch: 'SUBMIT DISPATCH',
    raisedTickets: 'RAISED TICKETS',

    supportProtocolTag: 'SUPPORT PROTOCOL V2.1',
    infoArchitectureTag: 'INFORMATION ARCHITECTURE',
    strategicClassificationTag: 'STRATEGIC CLASSIFICATION',
    detailedDossierTag: 'DETAILED DOSSIER',
    intelligenceBriefingTitle: 'INTELLIGENCE BRIEFING',
    describeSituationPlaceholder: 'DESCRIBE YOUR SITUATION IN DETAIL...',
    supportingAssetsTag: 'SUPPORTING ASSETS',
    attachmentsTitle: 'ATTACHMENTS',
    submitAssetsLabel: 'SUBMIT ASSETS',
    fileTypesMax: 'JPG, PNG, PDF (MAX 10MB)',
    establishCommunication: 'ESTABLISH COMMUNICATION.',
    operativesResponseDesc: 'Our operatives typically respond within a 24-hour window. Discovery of the intersection of technology, design, and classical theory remains our primary protocol.',
    intelligenceLogTag: 'INTELLIGENCE LOG',
    protocolIdCol: 'PROTOCOL ID',
    briefingSubjectCol: 'BRIEFING SUBJECT',
    classificationCol: 'CLASSIFICATION',
    currentStateCol: 'CURRENT STATE',
    timestampCol: 'TIMESTAMP',
    retrievingDispatches: 'RETRIEVING DISPATCHES...',
    noDispatchesFound: 'No active dispatches found in archive.',

    // Contact Page
    getInTouch: 'GET IN TOUCH',
    contactUs: 'CONTACT US.',
    contactDesc: 'We are here to help! Whether you have questions about our courses, need technical support, or just want to share feedback, the Support Team is always ready to assist you.',
    sendMessage: 'SEND A MESSAGE',
    yourNameLabel: 'YOUR NAME',
    phoneCodeLabel: 'CODE',
    subjectLabel: 'SUBJECT',
    messageLabel: 'MESSAGE',
    enterYourName: 'Enter your name',
    enterYourEmail: 'Enter your email',
    enterYourPhone: 'Enter your phone number',
    tellUsHowHelp: 'Tell us how we can help you... (optional)',
    sendMessageBtn: 'SEND MESSAGE',
    emailSupport: 'Email Support',
    officeAddress: 'Office Address',
    feedbackSuggestions: 'Feedback & Suggestions',
    socialMedia: 'Social Media',

    // Auth & Modals
    confirmLogoutTitle: 'Confirm Logout?',
    confirmLogoutMessage: 'You are about to terminate your active session. You will be returned to the main portal shortly.',
    logOutNowBtn: 'LOG OUT NOW',
    welcomeBackTitle: 'Welcome back',
    loginSubtitle: 'ENTER YOUR CREDENTIALS TO ACCESS THE VANGUARD.',
    continueWithGoogle: 'CONTINUE WITH GOOGLE',
    joinTheCircleTitle: 'Join the circle',
    signupSubtitle: 'COMMENCE YOUR PATH TO MASTERY.',
    joinWithGoogle: 'JOIN WITH GOOGLE',
    sendOtpBtn: 'SEND OTP',
    resendOtpBtn: 'RESEND OTP',
    sendingOtpBtn: 'SENDING...',
    enterOtpPlaceholder: 'Enter OTP',
    verifyBtn: 'VERIFY',
    verifyingBtn: 'VERIFYING...',
    verifiedBtn: 'VERIFIED',
    requestResetLink: 'Request a reset link',
    requestResetLinkDesc: 'Enter the email attached to your account. If it exists, we will send a link to reset the password.',
    sendResetLinkBtn: 'SEND RESET LINK',

    // Hero & Landing
    heroBadge: 'NEXT-GEN LEARNING PLATFORM',
    heroTitleLine1: 'MASTER THE SKILLS FOR THE',
    heroTitleLine2: 'DIGITAL FUTURE',
    heroDesc: 'Accelerate your career with industry-aligned courses, real-world projects, live mentorship, and an active developer community.',
    exploreCourses: 'EXPLORE COURSES',
    getStarted: 'GET STARTED',
    activeLearners: 'Active Learners',
    activeStudents: 'Active Students',
    completionRate: 'Completion Rate',
    topRating: 'User Rating',
    averageRating: 'Average Rating',

    // Gigs & Jobs
    gigsTitle: 'Gigs',
    gigsSubtitle: 'Explore high-impact opportunities and industry projects',
    filterBy: 'FILTER BY',
    categoryDesignBranding: 'Design & Branding',
    categoryContentCopywriting: 'Content & Copywriting',
    categoryVideoAudio: 'Video & Audio',
    categoryMarketingGrowth: 'Marketing & Growth',
    categoryTechWebsite: 'Tech & Website',
    categorySalesClientwork: 'Sales & Client Work',
    jobRole: 'Role',
    jobLocation: 'Location',
    jobReportTo: 'Report to',
    jobWorkingDays: 'Working days',
    jobTimings: 'Timings',
    positionOverview: 'Position Overview',
    applyNow: 'APPLY NOW',
    postedText: 'Posted',
    noGigsFound: 'No gigs found in this category',

    // News & Dispatches
    archive2024: 'ARCHIVE 2024',
    latestTitle: 'Latest',
    dispatchesTitle: 'Dispatches',
    searchNewsPlaceholder: 'Search news by topic...',
    viewsText: 'VIEWS',
    likesText: 'LIKES',

    // Create Job Modal
    createJobPostTitle: 'Create Job Post',
    editJobPostTitle: 'Edit Job Post',
    createJobPostDesc: 'Fill out the details to post your job',
    editJobPostDesc: 'Update the details of your job',
    jobTitleLabel: 'Job Title *',
    jobTitlePlaceholder: 'Enter job title',
    jobDescriptionLabel: 'Job Description *',
    jobDescriptionPlaceholder: 'Describe the job requirements, responsibilities, and qualifications...',
    jobDetailsHeader: 'Job Details',
    experienceLevelLabel: 'Experience Level *',
    jobModeLabel: 'Job Mode *',
    locationTypeLabel: 'Location Type *',
    currencyLabel: 'Currency *',
    budgetDetailsHeader: 'Budget Details',
    budgetRangeHeader: 'Budget Range',
    minBudgetLabel: 'Minimum Budget *',
    maxBudgetLabel: 'Maximum Budget *',
    durationHeader: 'Duration',
    durationValueLabel: 'Duration Value *',
    durationUnitLabel: 'Duration Unit *',
    requiredSkillsHeader: 'Required Skills',
    addSkillBtn: 'Add Skill',
    addSkillPlaceholder: 'Add a skill',
    jobImageHeader: 'Job Image',
    thumbnailLabel: 'Thumbnail Image',
    chooseFileBtn: 'Choose File',
    noFileChosen: 'No file chosen',
    createJobBtn: 'Create Job',
    updateJobBtn: 'Update Job',
    creatingJob: 'Creating...',
    updatingJob: 'Updating...',

    // Landing Sections & Home Page
    growthTitle: 'VIBRANT GROWTH & CAREER ACCELERATION',
    growthDesc: 'Transform your passion into professional excellence with personalized roadmaps and continuous support.',
    growthHeadline: 'Accelerate Your Tech Career',
    growthSub: 'Structured learning paths designed by industry experts with hands-on real world projects.',
    
    selectedForYou: 'SELECTED FOR YOU',
    selectionTitle: 'The Selection',
    selectionSub: 'A hand-picked collection of lessons built to help you grow faster. Learn the best strategies from our most popular courses.',
    exploreAll: 'EXPLORE ALL',

    // CTAs & Badges
    startModule: 'START THE MODULE',
    viewJob: 'VIEW JOB',
    learnMore: 'LEARN MORE',
    careerSpotlight: 'CAREER SPOTLIGHT',
    curatedModule: 'CURATED MODULE',
    registerNow: 'REGISTER NOW',
    newBadge: 'NEW',

    // Forum & Assessment CTAs
    startNewTopic: 'START NEW TOPIC',
    contributeCollective: 'Contribute to the collective intelligence',
    popularTags: 'POPULAR TAGS',
    startAssessment: 'START ASSESSMENT',
    retakeProtocol: 'RETAKE PROTOCOL',
    systemOverview: 'SYSTEM OVERVIEW',
    noNeuralData: 'No Neural Data Found',
    cognitiveNotCalibrated: 'Your cognitive frequency has not been calibrated. Complete the assessment to unlock personalized architecture.',
    intelligenceNetwork: 'Intelligence Network',

    // Auth & Reset Password
    resetPasswordTitle: 'PASSWORD RESET',
    newPassword: 'NEW PASSWORD',
    confirmPassword: 'CONFIRM PASSWORD',
    token: 'TOKEN',
    orCreateAccount: 'OR CREATE ACCOUNT',
    orEmail: 'OR EMAIL',
    accessTier: 'ACCESS TIER',

    // Placeholders & Filter Tabs
    searchArchive: 'SEARCH ARCHIVE',
    inProgress: 'IN PROGRESS',
    wishlist: 'WISHLIST',
    enterFullIdentity: 'ENTER FULL IDENTITY',
    emailCoordinates: 'EMAIL COORDINATES',
    communicationLine: 'COMMUNICATION LINE',
    briefingSubject: 'BRIEFING SUBJECT',
    enterName: 'ENTER NAME',
    phoneNumber: 'PHONE NUMBER',

    // News & Dossier
    backToNews: 'BACK TO ALL NEWS',
    scrollToUnlock: 'SCROLL TO UNLOCK ARCHIVE',
    endOfArchive: 'END OF INTELLIGENCE DOSSIER',
    prevDispatch: 'PREVIOUS DISPATCH',
    nextDispatch: 'NEXT DISPATCH',

    // Forum Stats & Details
    likes: 'LIKES',
    replies: 'REPLIES',
    postReply: 'POST A REPLY',
    forumStats: 'FORUM STATS',
    popularDiscourse: 'POPULAR DISCOURSE',
    backToForum: 'BACK TO FORUM',

    // Catalog & Fallbacks
    failedToLoad: 'FAILED TO LOAD COURSES',
    noCoursesAvailable: 'NO COURSES AVAILABLE',
    berlin: 'BERLIN',
    remotelyAvailable: 'REMOTELY AVAILABLE',

    // Checkout & Features
    protocolActive: 'PROTOCOL ACTIVE',
    selectCoupon: 'SELECT COUPON',
    sslSecured: 'SSL SECURED',
    instantActivation: 'INSTANT ACTIVATION',
    live: 'LIVE',
    seePricing: 'SEE PRICING',

    howWeHelp: 'HOW WE HELP / EXPERTISE',
    designedToGrow: 'Designed to Grow Your Business',
    brandFeaturesSub: 'Clear strategies to scale your agency and land high-paying clients.',
    focus01Title: 'Smart Growth Systems',
    focus01Desc: 'Automate your work using smart systems. Build your process once and let it run forever without needing a huge team.',
    focus02Title: 'Build Your Influence',
    focus02Desc: 'Create a personal brand that people trust. Attract top-tier clients by standing out as a true expert in your field.',
    focus03Title: 'Track Your Progress',
    focus03Desc: 'Get a clear view of your business results. Easily track your profits, costs, and team performance all in one place.',
    focus04Title: 'A Proven Path',
    focus04Desc: 'Use our simple framework to grow your income and build a business that runs smoothly even when you are away.',

    faqTitle: 'FREQUENTLY ASKED QUESTIONS',
    faqSubtitle: 'Everything you need to know about our courses, certification, and career placement support.',
    
    comparisonTitle: 'EDRILLA VS TRADITIONAL LEARNING',
    comparisonSubtitle: 'Discover why thousands of professionals choose our execution-focused learning model.',
    edrillaAdvantage: 'The Edrilla Advantage',
    traditionalWay: 'Traditional Education',
    
    benefitsTitle: 'WHY LEARN WITH US',
    benefitsSub: 'Built for high performers seeking real outcomes, not just video views.',
    
    guaranteeTitle: '100% SATISFACTION GUARANTEE',
    guaranteeDesc: 'Try any course risk-free for 14 days. If you are not completely satisfied, get a full refund with no questions asked.',
    
    solutionTitle: 'THE COMPLETE SKILL-BUILDING SOLUTION',
    solutionSub: 'From foundational theory to production-ready applications.',
    
    catalogTitle: 'CURATED COURSE CATALOG',
    catalogSub: 'Handcrafted learning tracks tailored for modern high-demand roles.',
    
    masterclassTitle: 'EXPERT MASTERCLASSES',
    masterclassSub: 'Exclusive live sessions led by industry pioneers and senior tech leaders.',

    // Footer
    sloganMagic: "Education engineered for",
    sloganMagicBold: "MASTERY",
    sloganGuarantee: "The standard for",
    sloganGuaranteeBold: "EXCELLENCE",
    ambitionExecution: "Where Ambition Meets Execution",
    privacyPolicy: "Privacy Policy",
    services: "Services",
    blog: "Blog",
    work: "Work",
    contact: "Contact",

    // Dashboard Components & Sidebar
    systemActive: "System Active",
    welcomeHello: "Hello",
    onTrack: "You are currently on track. Accelerate your learning by continuing your latest module.",
    currentXP: "Current XP",
    carrierLevel: "Carrier Level",
    weeklyGoals: "Weekly Goals",
    weeklyGoalsTitle: "Weekly Study Goals",
    weeklyGoalsSub: "Keep your streak alive by completing target hours every week.",
    focusConsistency: "Focusing on Consistency",
    enrolledCourses: "Enrolled Courses",
    completed: "Completed",
    completedModules: "Completed Modules",
    certificatesEarned: "Certificates Earned",
    totalXP: "Total XP Points",
    activeCoursesCount: "Active Courses",
    editGoals: "Edit Goals",
    continueLearning: "Continue Learning",
    progress: "Progress",
    resume: "Resume",
    topLearners: "Top Learners",
    upcomingDeadlines: "Upcoming Deadlines",
    recentActivity: "Recent Activity",
    recentActivityTitle: "Recent Activity Log",
    viewAllActivity: "View All Activity",
    auditTrail: "Audit Trail",
    noPendingAssignments: "No pending assignments",
    submissionRequired: "Submission Required",
    pending: "PENDING",

    // Authentication & Profile
    welcomeBack: "Welcome Back",
    signInAccount: "Sign in to your account",
    signupTitle: "Create Your Account",
    signupSub: "Start your journey today with full access to our learning platform.",
    createAccount: "Create Your Account",
    emailAddress: "Email Address",
    password: "Password",
    rememberMe: "Remember me",
    forgotPassword: "Forgot password?",
    donthaveAccount: "Don't have an account?",
    alreadyHaveAccount: "Already have an account?",
    signUpNow: "Sign up now",
    fullName: "Full Name",
    sendResetLink: "Send Reset Link",
    profileTitle: "User Profile Settings",
    profileSub: "Manage your personal information, security preferences, and connected accounts.",
    editProfile: "Edit Profile",
    saveChanges: "Save Changes",
    purchasesTitle: "My Purchases & Invoices",
    purchasesSub: "View all your past course enrollments, transaction receipts, and payment history.",
    myCoursesTitle: "My Enrolled Courses",
    myCoursesSub: "Track your course progress, resume modules, and access learning certificates.",
    liveClassesTitle: "Live Interactive Classes",
    joinClass: "JOIN LIVE SESSION",
    supportTitle: "Help & Support Center",
    supportSub: "Have questions or need assistance? Reach out to our dedicated support team 24/7.",

    // Course & Page UI
    allCoursesTitle: "EXPLORE ALL COURSES",
    searchCoursesPlaceholder: "Search by course title, skill, or instructor...",
    categoryAll: "All Categories",
    categoryWeb: "Web Development",
    categoryAI: "AI & Machine Learning",
    categoryDesign: "UI/UX Design",
    categoryData: "Data Science",
    enrollNow: "ENROLL NOW",
    viewDetails: "VIEW DETAILS",
    rating: "Rating",
    studentsEnrolled: "Students",
    forumTitle: "COMMUNITY DISCUSSIONS",
    forumSubtitle: "Ask questions, share insights, and connect with fellow developers.",
    gigTitle: "JOB & FREELANCE OPPORTUNITIES",
    gigSubtitle: "Discover hand-picked gigs and full-time tech roles tailored for your skill set.",
    newsTitle: "TECH INSIGHTS & UPDATES",
    newsSubtitle: "Stay updated with the latest trends in tech, design, and career growth.",
    contactTitle: "Get in Touch with Us",
    contactSub: "We would love to hear from you. Send us a message and we will respond as soon as possible.",
  },
  hi: {
    // Navigation & General
    home: 'मुख्य पृष्ठ',
    ourCourses: 'हमारे कोर्स',
    forum: 'मंच (फोरम)',
    gig: 'गिग (नौकरियां)',
    news: 'समाचार',
    dashboard: 'डैशबोर्ड',
    signIn: 'साइन इन',
    logOut: 'लॉग आउट',
    liveClasses: 'लाइव कक्षाएं',
    profile: 'प्रोफ़ाइल',
    myActivity: 'मेरी गतिविधि',
    myForum: 'मेरा मंच',
    mySubmissions: 'मेरे सबमिशन',
    myPurchases: 'मेरी खरीदारी',
    myCourses: 'मेरे कोर्स',
    allCourses: 'सभी कोर्स',
    jobPostings: 'जॉब पोस्टिंग',
    support: 'सहायता और सहायता केंद्र',

    // Profile & User Info
    security: 'सुरक्षा',
    academic: 'शैक्षणिक',
    profileDetails: 'प्रोफ़ाइल विवरण',
    fullNameLabel: 'पूरा नाम',
    emailAddressLabel: 'ईमेल पता',
    phoneNumberLabel: 'फ़ोन नंबर',
    locationLabel: 'स्थान',
    aboutMeBio: 'मेरे बारे में / बायो',
    companyNameLabel: 'कंपनी का नाम',
    gstNumberLabel: 'जीएसटी नंबर',
    saveChangesBtn: 'परिवर्तन सहेजें',
    savingState: 'सहेज रहा है...',
    changesSavedMsg: 'परिवर्तन सहेजे गए',
    currentPasswordLabel: 'वर्तमान पासवर्ड',
    newPasswordLabel: 'नया पासवर्ड',
    confirmPasswordLabel: 'पासवर्ड की पुष्टि करें',
    updatePasswordBtn: 'पासवर्ड अपडेट करें',
    cancelBtn: 'रद्द करें',
    studentRole: 'छात्र',
    memberRole: 'सदस्य',
    coursesStat: 'कोर्स',
    postsStat: 'पोस्ट',
    certificatesStat: 'प्रमाणपत्र',
    personalityArchetype: 'व्यक्तित्व का प्रकार',
    coreDescription: 'मुख्य विवरण',
    bioSummary: 'बायो सारांश',
    noBioRecorded: 'रजिस्ट्री में कोई बायो दर्ज नहीं है।',
    badgesTitle: 'बैज',
    earlyAdopter: 'प्रारंभिक उपयोगकर्ता',
    verifiedUser: 'सत्यापित उपयोगकर्ता',
    accountInfo: 'खाता जानकारी',
    lockedLabel: 'लॉक',

    // Live Classes
    liveSignal: 'लाइव सिग्नल',
    noClassesActive: 'वर्तमान में कोई कक्षाएं सक्रिय नहीं हैं।',
    meetingDisconnected: 'मीटिंग डिस्कनेक्ट हो गई',
    disconnectedDesc: 'आप इस सत्र से हट गए हैं या डिस्कनेक्ट हो गए हैं।',
    reconnecting: 'पुनः कनेक्ट हो रहा है...',
    rejoin: 'पुनः जुड़ें',
    dismiss: 'खारिज करें',
    secureBroadcast: 'सुरक्षित प्रसारण',
    allScheduledClasses: 'सभी निर्धारित कक्षाएं',

    // Academic & Education
    educationHistory: 'शिक्षा का इतिहास',
    viewAll: 'सभी देखें',
    noHistoryRecorded: 'कोई इतिहास दर्ज नहीं है',
    addEducationDetails: 'अपनी शिक्षा का विवरण जोड़ें',
    addEducation: 'शिक्षा जोड़ें',
    myDocuments: 'मेरे दस्तावेज़',
    uploadFile: 'फ़ाइल अपलोड करें',

    // My Forum / Discourse
    myDiscourse: 'मेरी चर्चाएँ',
    discourseSub: 'आपके सामुदायिक योगदान और विषयों का संग्रह',
    totalThreads: 'कुल थ्रेड्स',
    engagement: 'सहभागिता',
    calibrations: 'कैलिब्रेशंस',
    noContributionsFound: 'कोई योगदान नहीं मिला',
    noThreadsStarted: 'आपने अभी तक कोई फ़ोरम थ्रेड शुरू नहीं किया है',

    // Submissions
    assignmentArchive: 'असाइनमेंट संग्रह',
    submissionsSub: 'अपने रणनीतिक सबमिशन और प्रदर्शन मेट्रिक्स को ट्रैक करें',
    performance: 'प्रदर्शन',

    // Purchases & Ledger
    archiveLedger: 'संग्रह और बहीखाता',
    purchasesLedgerSub: 'Edrilla नेटवर्क पर बौद्धिक अधिग्रहण और संस्थागत निवेश का स्थायी रिकॉर्ड।',
    moduleArchive: 'मॉड्यूल संग्रह',
    acquisition: 'अधिग्रहण तिथि',
    amount: 'राशि',
    actions: 'कार्रवाई',
    receipt: 'रसीद',
    refund: 'रिफंड',

    // Messages
    messagesTitle: 'संदेश',
    activeChats: 'सक्रिय चैट:',
    chatsTab: 'चैट',
    groupsTab: 'समूह',
    searchMessages: 'संदेश खोजें...',
    allFilter: 'सभी',
    unreadFilter: 'अपठित',
    loadingChats: 'चैट लोड हो रही है...',
    connectionError: 'कनेक्शन त्रुटि',
    retryBtn: 'पुनः प्रयास करें',
    reconnectBtn: 'पुनः कनेक्ट करें',
    noMessagesFound: 'कोई संदेश नहीं मिला',
    participants: 'प्रतिभागी',
    searchParticipants: 'प्रतिभागियों की खोज करें...',
    clearChat: 'चैट साफ करें',
    selectConversation: 'मैसेजिंग शुरू करने के लिए कोई बातचीत चुनें',
    messagesSecure: 'आपके संदेश सुरक्षित हैं',
    typeMessage: 'एक संदेश टाइप करें...',

    // My Courses / Curriculum
    continuingEducation: 'सतत शिक्षा',
    myCurriculum: 'मेरा पाठ्यक्रम',
    activeCoursesLabel: 'सक्रिय पाठ्यक्रम',
    completionRateLabel: 'पूर्णता दर',
    searchBtn: 'खोजें',

    // All Courses Catalog
    curatedCatalog: 'क्यूरेटेड कैटलॉग',
    ourCoursesTitle: 'हमारे पाठ्यक्रम',
    availableStat: 'उपलब्ध',
    newTodayStat: 'आज नया',
    allCoursesTab: 'सभी पाठ्यक्रम',
    businessTab: 'व्यवसाय',
    digitalMarketingTab: 'डिजिटल मार्केटिंग',
    showingCoursesLabel: 'पाठ्यक्रम दिखाए जा रहे हैं',
    advancedFiltersBtn: 'उन्नत फ़िल्टर',

    // Forum
    totalTopicsLabel: 'कुल विषय',
    activeUsersLabel: 'सक्रिय उपयोगकर्ता',
    thisWeekLabel: 'इस सप्ताह',
    recentDiscourse: 'हाल की चर्चा',
    filterByIntelligence: 'इंटेलिजेंस द्वारा फ़िल्टर करें',

    // Job Posts
    manageJobOpps: 'अपने प्रकाशित नौकरी के अवसरों को प्रबंधित और ट्रैक करें',
    createNewPost: 'नई पोस्ट बनाएं',
    totalPostsLabel: 'कुल पोस्ट',
    activeLeadsLabel: 'सक्रिय लीड्स',
    totalProposalsLabel: 'कुल प्रस्ताव',
    myPublications: 'मेरे प्रकाशन',

    // Floating Navbar Popups
    recentDispatches: 'हाल के संदेश',
    markAllRead: 'सभी को पढ़ा हुआ चिह्नित करें',
    viewAllAlerts: 'सभी अलर्ट देखें',
    protocolXPAcquired: 'प्रोटोकॉल एक्सपी प्राप्त किया',
    xpDesc: 'कलर थ्योरी बेसिक के लिए +250',
    moduleUploaded: 'मॉड्यूल अपलोड किया गया',
    moduleUploadedDesc: 'सिनेमैटोग्राफी में नई सामग्री',
    communitySignal: 'कम्युनिटी सिग्नल',
    communitySignalDesc: 'मार्कस आर. ने आपके थ्रेड का जवाब दिया',
    rankCarrier: 'रैंक कैरियर',
    identityProfile: 'पहचान प्रोफ़ाइल',
    systemSettings: 'सिस्टम सेटिंग्स',
    accessKeys: 'एक्सेस कुंजियाँ',

    // Support Screen
    supportCenter: 'सहायता केंद्र',
    activeDispatches: 'सक्रिय प्रेषण',
    raiseTicket: 'टिकट उठाएं',
    myTickets: 'मेरे टिकट',
    contactInfo: 'संपर्क जानकारी',
    supportCategory: 'सहायता श्रेणी',
    intelligenceBriefing: 'इंटेलीजेंस ब्रीफिंग',
    attachments: 'संलग्नक',
    submitDispatch: 'प्रेषण जमा करें',
    raisedTickets: 'उठाए गए टिकट',

    supportProtocolTag: 'सहायता प्रोटोकॉल V2.1',
    infoArchitectureTag: 'सूचना वास्तुकला',
    strategicClassificationTag: 'रणनीतिक वर्गीकरण',
    detailedDossierTag: 'विस्तृत डोजियर',
    intelligenceBriefingTitle: 'इंटेलीजेंस ब्रीफिंग',
    describeSituationPlaceholder: 'अपनी स्थिति का विस्तार से वर्णन करें...',
    supportingAssetsTag: 'सहायक संपत्ति',
    attachmentsTitle: 'संलग्नक',
    submitAssetsLabel: 'संपत्ति जमा करें',
    fileTypesMax: 'JPG, PNG, PDF (अधिकतम 10MB)',
    establishCommunication: 'संचार स्थापित करें।',
    operativesResponseDesc: 'हमारे प्रतिनिधि आमतौर पर 24 घंटे की अवधि के भीतर जवाब देते हैं। प्रौद्योगिकी, डिजाइन और शास्त्रीय सिद्धांत के प्रतिच्छेदन की खोज हमारा प्राथमिक प्रोटोकॉल है।',
    intelligenceLogTag: 'इंटेलीजेंस लॉग',
    protocolIdCol: 'प्रोटोकॉल आईडी',
    briefingSubjectCol: 'ब्रीफिंग विषय',
    classificationCol: 'वर्गीकरण',
    currentStateCol: 'वर्तमान स्थिति',
    timestampCol: 'समय',
    retrievingDispatches: 'प्रेषण प्राप्त किया जा रहा है...',
    noDispatchesFound: 'संग्रह में कोई सक्रिय प्रेषण नहीं मिला।',

    // Contact Page
    getInTouch: 'संपर्क करें',
    contactUs: 'हमसे संपर्क करें।',
    contactDesc: 'हम यहाँ आपकी मदद के लिए हैं! चाहे आपके पास हमारे पाठ्यक्रमों के बारे में प्रश्न हों, तकनीकी सहायता की आवश्यकता हो, या प्रतिक्रिया साझा करना चाहते हों, सहायता टीम हमेशा आपकी सहायता के लिए तैयार है।',
    sendMessage: 'एक संदेश भेजें',
    yourNameLabel: 'आपका नाम',
    phoneCodeLabel: 'कोड',
    subjectLabel: 'विषय',
    messageLabel: 'संदेश',
    enterYourName: 'अपना नाम दर्ज करें',
    enterYourEmail: 'अपना ईमेल दर्ज करें',
    enterYourPhone: 'अपना फ़ोन नंबर दर्ज करें',
    tellUsHowHelp: 'बताएं कि हम आपकी क्या मदद कर सकते हैं... (वैकल्पिक)',
    sendMessageBtn: 'संदेश भेजें',
    emailSupport: 'ईमेल सहायता',
    officeAddress: 'कार्यालय का पता',
    feedbackSuggestions: 'प्रतिक्रिया और सुझाव',
    socialMedia: 'सोशल मीडिया',

    // Auth & Modals
    confirmLogoutTitle: 'लॉगआउट की पुष्टि करें?',
    confirmLogoutMessage: 'आप अपना सक्रिय सत्र समाप्त करने वाले हैं। आपको जल्द ही मुख्य पोर्टल पर वापस भेज दिया जाएगा।',
    logOutNowBtn: 'अभी लॉगआउट करें',
    welcomeBackTitle: 'वापसी पर स्वागत है',
    loginSubtitle: 'अपने खाते में प्रवेश करने के लिए क्रेडेंशियल दर्ज करें।',
    continueWithGoogle: 'गूगल के साथ आगे बढ़ें',
    joinTheCircleTitle: 'समुदाय से जुड़ें',
    signupSubtitle: 'महारत की अपनी यात्रा शुरू करें।',
    joinWithGoogle: 'गूगल के साथ जुड़ें',
    sendOtpBtn: 'ओटीपी भेजें',
    resendOtpBtn: 'पुनः ओटीपी भेजें',
    sendingOtpBtn: 'भेजा जा रहा है...',
    enterOtpPlaceholder: 'ओटीपी दर्ज करें',
    verifyBtn: 'सत्यापित करें',
    verifyingBtn: 'सत्यापित किया जा रहा है...',
    verifiedBtn: 'सत्यापित',
    requestResetLink: 'रीसेट लिंक का अनुरोध करें',
    requestResetLinkDesc: 'अपने खाते से जुड़ा ईमेल दर्ज करें। यदि यह मौजूद है, तो हम पासवर्ड रीसेट करने का लिंक भेजेंगे।',
    sendResetLinkBtn: 'रीसेट लिंक भेजें',

    // Hero & Landing
    heroBadge: 'नेक्स्ट-जनरेशन लर्निंग प्लेटफॉर्म',
    heroTitleLine1: 'डिजिटल भविष्य के लिए',
    heroTitleLine2: 'कौशल में महारत हासिल करें',
    heroDesc: 'उद्योग-संरेखित पाठ्यक्रमों, वास्तविक दुनिया की परियोजनाओं, लाइव मेंटरशिप और सक्रिय डेवलपर समुदाय के साथ अपने करियर को गति दें।',
    exploreCourses: 'कोर्स देखें',
    getStarted: 'शुरू करें',
    activeLearners: 'सक्रिय शिक्षार्थी',
    activeStudents: 'सक्रिय छात्र',
    completionRate: 'पूर्णता दर',
    topRating: 'उपयोगकर्ता रेटिंग',
    averageRating: 'औसत रेटिंग',

    // Gigs & Jobs
    gigsTitle: 'गिग्स',
    gigsSubtitle: 'उच्च-प्रभाव वाले अवसरों और उद्योग परियोजनाओं का अन्वेषण करें',
    filterBy: 'फ़िल्टर करें',
    categoryDesignBranding: 'डिजाइन और ब्रांडिंग',
    categoryContentCopywriting: 'सामग्री और कॉपीराइटिंग',
    categoryVideoAudio: 'वीडियो और ऑडियो',
    categoryMarketingGrowth: 'मार्केटिंग और ग्रोथ',
    categoryTechWebsite: 'टेक और वेबसाइट',
    categorySalesClientwork: 'बिक्री और क्लाइंट कार्य',
    jobRole: 'भूमिका',
    jobLocation: 'स्थान',
    jobReportTo: 'रिपोर्टिंग',
    jobWorkingDays: 'कार्य दिवस',
    jobTimings: 'समय',
    positionOverview: 'पद विवरण',
    applyNow: 'अभी आवेदन करें',
    postedText: 'पोस्ट किया गया',
    noGigsFound: 'इस श्रेणी में कोई गिग्स नहीं मिले',

    // News & Dispatches
    archive2024: 'संग्रह 2024',
    latestTitle: 'नवीनतम',
    dispatchesTitle: 'प्रेषण',
    searchNewsPlaceholder: 'विषय के अनुसार समाचार खोजें...',
    viewsText: 'दृश्य',
    likesText: 'पसंद',

    // Create Job Modal
    createJobPostTitle: 'जॉब पोस्ट बनाएं',
    editJobPostTitle: 'जॉब पोस्ट संपादित करें',
    createJobPostDesc: 'अपनी जॉब पोस्ट करने के लिए विवरण भरें',
    editJobPostDesc: 'अपनी जॉब का विवरण अपडेट करें',
    jobTitleLabel: 'जॉब शीर्षक *',
    jobTitlePlaceholder: 'जॉब शीर्षक दर्ज करें',
    jobDescriptionLabel: 'जॉब विवरण *',
    jobDescriptionPlaceholder: 'जॉब की आवश्यकताओं, जिम्मेदारियों और योग्यताओं का वर्णन करें...',
    jobDetailsHeader: 'जॉब विवरण',
    experienceLevelLabel: 'अनुभव स्तर *',
    jobModeLabel: 'जॉब मोड *',
    locationTypeLabel: 'स्थान का प्रकार *',
    currencyLabel: 'मुद्रा *',
    budgetDetailsHeader: 'बजट विवरण',
    budgetRangeHeader: 'बजट सीमा',
    minBudgetLabel: 'न्यूनतम बजट *',
    maxBudgetLabel: 'अधिकतम बजट *',
    durationHeader: 'अवधि',
    durationValueLabel: 'अवधि का मान *',
    durationUnitLabel: 'अवधि की इकाई *',
    requiredSkillsHeader: 'आवश्यक कौशल',
    addSkillBtn: 'कौशल जोड़ें',
    addSkillPlaceholder: 'कौशल जोड़ें',
    jobImageHeader: 'जॉब छवि',
    thumbnailLabel: 'थंबनेल छवि',
    chooseFileBtn: 'फ़ाइल चुनें',
    noFileChosen: 'कोई फ़ाइल नहीं चुनी गई',
    createJobBtn: 'जॉब बनाएं',
    updateJobBtn: 'जॉब अपडेट करें',
    creatingJob: 'बनाया जा रहा है...',
    updatingJob: 'अपडेट किया जा रहा है...',

    // Landing Sections & Home Page
    growthTitle: 'जीवंत विकास और करियर त्वरण',
    growthDesc: 'व्यक्तिगत रोडमैप और निरंतर समर्थन के साथ अपने जुनून को पेशेवर उत्कृष्टता में बदलें।',
    growthHeadline: 'अपने टेक करियर को गति दें',
    growthSub: 'वास्तविक दुनिया के प्रोजेक्ट्स के साथ उद्योग विशेषज्ञों द्वारा डिज़ाइन किए गए शिक्षण पथ।',
    
    selectedForYou: 'आपके लिए चयनित',
    selectionTitle: 'विशेष चयन',
    selectionSub: 'आपको तेजी से आगे बढ़ाने के लिए बनाए गए चुनिंदा पाठों का संग्रह। हमारे सबसे लोकप्रिय पाठ्यक्रमों से सर्वश्रेष्ठ रणनीतियाँ सीखें।',
    exploreAll: 'सभी देखें',

    // CTAs & Badges
    startModule: 'मॉड्यूल शुरू करें',
    viewJob: 'नौकरी देखें',
    learnMore: 'अधिक जानें',
    careerSpotlight: 'करियर स्पॉटलाइट',
    curatedModule: 'क्यूरेटेड मॉड्यूल',
    registerNow: 'अभी पंजीकरण करें',
    newBadge: 'नया',

    // Forum & Assessment CTAs
    startNewTopic: 'नया विषय शुरू करें',
    contributeCollective: 'सामूहिक ज्ञान में योगदान दें',
    popularTags: 'लोकप्रिय टैग',
    startAssessment: 'मूल्यांकन शुरू करें',
    retakeProtocol: 'पुनः टेस्ट लें',
    systemOverview: 'सिस्टम अवलोकन',
    noNeuralData: 'कोई डेटा नहीं मिला',
    cognitiveNotCalibrated: 'आपका संज्ञानात्मक विश्लेषण अभी नहीं हुआ है। व्यक्तिगत परिणाम अनलॉक करने के लिए मूल्यांकन पूरा करें।',
    intelligenceNetwork: 'इंटेलिजेंस नेटवर्क',

    // Auth & Reset Password
    resetPasswordTitle: 'पासवर्ड रीसेट',
    newPassword: 'नया पासवर्ड',
    confirmPassword: 'पासवर्ड की पुष्टि करें',
    token: 'टोकन',
    orCreateAccount: 'या खाता बनाएं',
    orEmail: 'या ईमेल करें',
    accessTier: 'एक्सेस स्तर',

    // Placeholders & Filter Tabs
    searchArchive: 'संग्रह खोजें',
    inProgress: 'प्रगति में',
    wishlist: 'इच्छासूची',
    enterFullIdentity: 'अपना पूरा नाम दर्ज करें',
    emailCoordinates: 'ईमेल आईडी दर्ज करें',
    communicationLine: 'फोन नंबर दर्ज करें',
    briefingSubject: 'विषय दर्ज करें',
    enterName: 'नाम दर्ज करें',
    phoneNumber: 'फोन नंबर',

    // News & Dossier
    backToNews: 'सभी समाचारों पर वापस जाएं',
    scrollToUnlock: 'आर्काइव अनलॉक करने के लिए स्क्रॉल करें',
    endOfArchive: 'इंटेलीजेंस डोजियर समाप्त',
    prevDispatch: 'पिछला संदेश',
    nextDispatch: 'अगला संदेश',

    // Forum Stats & Details
    likes: 'पसंद',
    replies: 'जवाब',
    postReply: 'उत्तर पोस्ट करें',
    forumStats: 'फोरम आंकड़े',
    popularDiscourse: 'लोकप्रिय चर्चा',
    backToForum: 'फोरम पर वापस जाएं',

    // Catalog & Fallbacks
    failedToLoad: 'कोर्स लोड करने में विफल',
    noCoursesAvailable: 'कोई कोर्स उपलब्ध नहीं है',
    berlin: 'बर्लिन',
    remotelyAvailable: 'दूरस्थ रूप से उपलब्ध',

    // Checkout & Features
    protocolActive: 'प्रोटोकॉल सक्रिय',
    selectCoupon: 'कूपन चुनें',
    sslSecured: 'एसएसएल सुरक्षित',
    instantActivation: 'तत्काल सक्रियण',
    live: 'लाइव',
    seePricing: 'मूल्य निर्धारण देखें',

    howWeHelp: 'हम कैसे मदद करते हैं / विशेषज्ञता',
    designedToGrow: 'आपके व्यवसाय को बढ़ाने के लिए डिज़ाइन किया गया',
    brandFeaturesSub: 'आपकी एजेंसी को बढ़ाने और उच्च भुगतान वाले ग्राहकों को आकर्षित करने की स्पष्ट रणनीतियाँ।',
    focus01Title: 'स्मार्ट ग्रोथ सिस्टम',
    focus01Desc: 'स्मार्ट सिस्टम का उपयोग करके अपने काम को स्वचालित करें। एक बार अपनी प्रक्रिया बनाएं और बिना किसी बड़ी टीम के इसे चलाएं।',
    focus02Title: 'अपना प्रभाव बनाएं',
    focus02Desc: 'एक व्यक्तिगत ब्रांड बनाएं जिस पर लोग भरोसा करें। अपने क्षेत्र में सच्चे विशेषज्ञ के रूप में उभरकर शीर्ष ग्राहकों को आकर्षित करें।',
    focus03Title: 'अपनी प्रगति को ट्रैक करें',
    focus03Desc: 'अपने व्यावसायिक परिणामों का स्पष्ट दृश्य प्राप्त करें। एक ही स्थान पर अपने लाभ, लागत और टीम के प्रदर्शन को आसानी से ट्रैक करें।',
    focus04Title: 'एक साबित मार्ग',
    focus04Desc: 'अपनी आय बढ़ाने और एक ऐसा व्यवसाय बनाने के लिए हमारे सरल ढाँचे का उपयोग करें जो आपके दूर होने पर भी सुचारू रूप से चले।',

    faqTitle: 'अक्सर पूछे जाने वाले प्रश्न (FAQ)',
    faqSubtitle: 'हमारे पाठ्यक्रमों, प्रमाणन और करियर सहायता के बारे में सब कुछ जानें।',
    
    comparisonTitle: 'पारंपरिक शिक्षा बनाम एड्रिला',
    comparisonSubtitle: 'जानें कि हजारों पेशेवर हमारे निष्पादन-केंद्रित शिक्षण मॉडल को क्यों चुनते हैं।',
    edrillaAdvantage: 'एड्रिला का लाभ',
    traditionalWay: 'पारंपरिक शिक्षा प्रणाली',
    
    benefitsTitle: 'हमारे साथ क्यों सीखें',
    benefitsSub: 'केवल वीडियो विचारों के लिए नहीं, बल्कि वास्तविक परिणाम चाहने वालों के लिए निर्मित।',
    
    guaranteeTitle: '100% संतुष्टि की गारंटी',
    guaranteeDesc: '14 दिनों के लिए किसी भी कोर्स को जोखिम-मुक्त आज़माएं। यदि आप पूरी तरह से संतुष्ट नहीं हैं, तो बिना किसी प्रश्न के पूर्ण रिफंड पाएं।',
    
    solutionTitle: 'संपूर्ण कौशल निर्माण समाधान',
    solutionSub: 'बुनियादी सिद्धांत से लेकर उत्पादन के लिए तैयार अनुप्रयोगों तक।',
    
    catalogTitle: 'क्यूरेटेड कोर्स कैटलॉग',
    catalogSub: 'आधुनिक उच्च-मांग भूमिकाओं के लिए तैयार किए गए शिक्षण ट्रैक।',
    
    masterclassTitle: 'विशेषज्ञ मास्टरक्लास',
    masterclassSub: 'उद्योग के अग्रदूतों और वरिष्ठ टेक लीडरों के नेतृत्व में विशेष लाइव सत्र।',

    // Footer
    sloganMagic: "महारत के लिए डिज़ाइन की गई",
    sloganMagicBold: "शिक्षा",
    sloganGuarantee: "उत्कृष्टता का",
    sloganGuaranteeBold: "मानक",
    ambitionExecution: "जहाँ महत्वाकांक्षा निष्पादन से मिलती है",
    privacyPolicy: "गोपनीयता नीति",
    services: "सेवाएं",
    blog: "ब्लॉग",
    work: "काम",
    contact: "संपर्क करें",

    // Dashboard Components & Sidebar
    systemActive: "सिस्टम सक्रिय",
    welcomeHello: "नमस्ते",
    onTrack: "आप वर्तमान में सही मार्ग पर हैं। अपने नवीनतम मॉड्यूल को जारी रखकर अपनी सीख बढ़ाएं।",
    currentXP: "वर्तमान एक्सपी",
    carrierLevel: "कैरियर स्तर",
    weeklyGoals: "साप्ताहिक लक्ष्य",
    weeklyGoalsTitle: "साप्ताहिक अध्ययन लक्ष्य",
    weeklyGoalsSub: "हर हफ्ते लक्ष्य घंटे पूरे करके अपनी स्ट्रीक को जीवित रखें।",
    focusConsistency: "निरंतरता पर ध्यान",
    enrolledCourses: "नामांकित कोर्स",
    completed: "पूरा किया गया",
    completedModules: "पूरे किए गए मॉड्यूल",
    certificatesEarned: "प्राप्त प्रमाण पत्र",
    totalXP: "कुल एक्सपी अंक",
    activeCoursesCount: "सक्रिय कोर्स",
    editGoals: "लक्ष्य संपादित करें",
    continueLearning: "सीखना जारी रखें",
    progress: "प्रगति",
    resume: "दोबारा शुरू करें",
    topLearners: "शीर्ष शिक्षार्थी",
    upcomingDeadlines: "आगामी समय सीमा",
    recentActivity: "हाल की गतिविधि",
    recentActivityTitle: "हाल की गतिविधि लॉग",
    viewAllActivity: "सभी गतिविधि देखें",
    auditTrail: "ऑडिट ट्रेल",
    noPendingAssignments: "कोई असाइनमेंट लंबित नहीं है",
    submissionRequired: "सबमिशन आवश्यक",
    pending: "लंबित",

    // Authentication & Profile
    welcomeBack: "वापसी पर स्वागत है",
    signInAccount: "अपने खाते में साइन इन करें",
    signupTitle: "अपना खाता बनाएं",
    signupSub: "हमारे शिक्षण मंच तक पूर्ण पहुंच के साथ आज ही अपनी यात्रा शुरू करें।",
    createAccount: "अपना खाता बनाएं",
    emailAddress: "ईमेल पता",
    password: "पासवर्ड",
    rememberMe: "मुझे याद रखें",
    forgotPassword: "पासवर्ड भूल गए?",
    donthaveAccount: "खाता नहीं है?",
    alreadyHaveAccount: "क्या आपके पास पहले से एक खाता मौजूद है?",
    signUpNow: "अभी साइन अप करें",
    fullName: "पूरा नाम",
    sendResetLink: "रीसेट लिंक भेजें",
    profileTitle: "उपयोगकर्ता प्रोफ़ाइल सेटिंग्स",
    profileSub: "अपनी व्यक्तिगत जानकारी, सुरक्षा प्राथमिकताओं और कनेक्टेड खातों को प्रबंधित करें।",
    editProfile: "प्रोफ़ाइल संपादित करें",
    saveChanges: "परिवर्तन सहेजें",
    purchasesTitle: "मेरी खरीदारी और इनवॉइस",
    purchasesSub: "अपने पिछले सभी कोर्स नामांकन, लेनदेन रसीदें और भुगतान इतिहास देखें।",
    myCoursesTitle: "मेरे नामांकित कोर्स",
    myCoursesSub: "अपनी पाठ्यक्रम प्रगति को ट्रैक करें, मॉड्यूल फिर से शुरू करें और प्रमाणपत्र एक्सेस करें।",
    liveClassesTitle: "लाइव इंटरेक्टिव कक्षाएं",
    joinClass: "लाइव सत्र में शामिल हों",
    supportTitle: "सहायता और समर्थन केंद्र",
    supportSub: "प्रश्न हैं या सहायता की आवश्यकता है? हमारी समर्पित सहायता टीम से 24/7 संपर्क करें।",

    // Course & Page UI
    allCoursesTitle: "सभी कोर्स देखें",
    searchCoursesPlaceholder: "कोर्स शीर्षक, कौशल या प्रशिक्षक द्वारा खोजें...",
    categoryAll: "सभी श्रेणियां",
    categoryWeb: "वेब डेवलपमेंट",
    categoryAI: "एआई और मशीन लर्निंग",
    categoryDesign: "यूआई/यूएक्स डिजाइन",
    categoryData: "डेटा साइंस",
    enrollNow: "अभी नामांकित करें",
    viewDetails: "विवरण देखें",
    rating: "रेटिंग",
    studentsEnrolled: "छात्र",
    forumTitle: "समुदाय चर्चाएं",
    forumSubtitle: "प्रश्न पूछें, विचार साझा करें और साथी डेवलपर्स के साथ जुड़ें।",
    gigTitle: "नौकरी और फ्रीलांस अवसर",
    gigSubtitle: "अपने कौशल सेट के लिए तैयार किए गए हाथ से चुने गए गिग और पूर्णकालिक टेक भूमिकाओं की खोज करें।",
    newsTitle: "टेक अंतर्दृष्टि और अपडेट",
    newsSubtitle: "तकनीक, डिज़ाइन और करियर विकास के नवीनतम रुझानों से अपडेट रहें।",
    contactTitle: "हमसे संपर्क करें",
    contactSub: "हम आपसे सुनना पसंद करेंगे। हमें एक संदेश भेजें और हम जल्द से जल्द जवाब देंगे।",
  }
}

const LanguageContext = createContext({
  language: 'en',
  setLanguage: () => {},
  t: (key) => key,
})

export const LanguageProvider = ({ children }) => {
  const [language, setLanguageState] = useState(() => {
    try {
      return localStorage.getItem('app_language') || 'en'
    } catch (e) {
      return 'en'
    }
  })

  const setLanguage = (lang) => {
    setLanguageState(lang)
    try {
      localStorage.setItem('app_language', lang)
    } catch (e) {
      console.warn('Failed to save language in localStorage', e)
    }
  }

  const t = (key) => {
    return translations[language]?.[key] || translations['en']?.[key] || key
  }

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  )
}

export const useLanguage = () => useContext(LanguageContext)
export default LanguageContext
