import React, { createContext, useContext, useState, useEffect } from 'react'

const translations = {
  en: {
    // Navigation & General
    home: 'Home',
    ourCourses: 'Our Courses',
    freeContent: 'Free Content',
    freePdfs: 'PDFs & Notes',
    freeClasses: 'Classes & Lectures',
    freeTests: 'Tests & Quizzes',
    exploreFreeContent: 'Explore Free Content',
    forum: 'Forum',
    gig: 'Gig',
    news: 'News',
    dashboard: 'Dashboard',
    signIn: 'Sign In',
    logOut: 'Log Out',
    liveClasses: 'Live Classes',
    profile: 'Profile',
    myActivity: 'My Activity',
    myForum: 'My Forum',
    mySubmissions: 'My Submissions',
    myPurchases: 'My Purchases',
    myCourses: 'My Courses',
    allCourses: 'All Courses',
    gsCourses: 'GS Courses',
    optionalCourses: 'Optional Courses',
    testSeries: 'Test Series',
    buyBooks: 'Buy Books',
    jobPostings: 'Job Postings',
    support: 'Support & Help',

    // Profile & User Info
    security: 'Security',
    academic: 'Academic',
    profileDetails: 'Profile Details',
    fullNameLabel: 'Full Name',
    emailAddressLabel: 'Email Address',
    phoneNumberLabel: 'Phone Number',
    locationLabel: 'Location',
    aboutMeBio: 'About Me / Bio',
    companyNameLabel: 'Company Name',
    gstNumberLabel: 'GST Number',
    saveChangesBtn: 'Save Changes',
    savingState: 'Saving...',
    changesSavedMsg: 'Changes Saved',
    currentPasswordLabel: 'Current Password',
    newPasswordLabel: 'New Password',
    confirmPasswordLabel: 'Confirm Password',
    updatePasswordBtn: 'Update Password',
    cancelBtn: 'Cancel',
    studentRole: 'Student',
    memberRole: 'Member',
    coursesStat: 'Courses',
    postsStat: 'Posts',
    certificatesStat: 'Certificates',
    personalityArchetype: 'Personality Archetype',
    coreDescription: 'Core Description',
    bioSummary: 'Bio Summary',
    noBioRecorded: 'No bio recorded in the registry.',
    badgesTitle: 'Badges',
    earlyAdopter: 'Early Adopter',
    verifiedUser: 'Verified User',
    accountInfo: 'Account Info',
    lockedLabel: 'Locked',

    // Live Classes
    liveSignal: 'LIVE SIGNAL',
    noClassesActive: 'No classes currently active.',
    meetingDisconnected: 'Meeting Disconnected',
    disconnectedDesc: 'You have left or been disconnected from this session.',
    reconnecting: 'RECONNECTING...',
    rejoin: 'REJOIN',
    dismiss: 'DISMISS',
    secureBroadcast: 'SECURE BROADCAST',
    allScheduledClasses: 'All Scheduled Classes',

    // Academic & Education
    educationHistory: 'Education History',
    viewAll: 'VIEW ALL',
    noHistoryRecorded: 'No History Recorded',
    addEducationDetails: 'Add your education details',
    addEducation: 'ADD EDUCATION',
    myDocuments: 'My Documents',
    uploadFile: 'UPLOAD FILE',

    // My Forum / Discourse
    myDiscourse: 'My Discourse',
    discourseSub: 'Archive of your community contributions and topics',
    totalThreads: 'TOTAL THREADS',
    engagement: 'ENGAGEMENT',
    calibrations: 'CALIBRATIONS',
    noContributionsFound: 'No contributions found',
    noThreadsStarted: "You haven't started any forum threads yet",

    // Submissions
    assignmentArchive: 'Assignment Archive',
    submissionsSub: 'Track your tactical submissions and performance metrics',
    performance: 'PERFORMANCE',

    // Purchases & Ledger
    archiveLedger: 'ARCHIVE & LEDGER',
    purchasesLedgerSub: 'Persistent record of course enrollments, consultation packages, and transaction receipts across Happy Life.',
    moduleArchive: 'MODULE ARCHIVE',
    acquisition: 'ACQUISITION',
    amount: 'AMOUNT',
    actions: 'ACTIONS',
    receipt: 'RECEIPT',
    refund: 'REFUND',

    // Messages
    messagesTitle: 'Messages',
    activeChats: 'Active chats:',
    chatsTab: 'CHATS',
    groupsTab: 'GROUPS',
    searchMessages: 'Search messages...',
    allFilter: 'ALL',
    unreadFilter: 'UNREAD',
    loadingChats: 'Loading chats...',
    connectionError: 'Connection Error',
    retryBtn: 'RETRY',
    reconnectBtn: 'RECONNECT',
    noMessagesFound: 'No messages found',
    participants: 'PARTICIPANTS',
    searchParticipants: 'Search participants...',
    clearChat: 'CLEAR CHAT',
    selectConversation: 'Select a conversation to start messaging',
    messagesSecure: 'Your messages are secure',
    typeMessage: 'Type a message...',

    // My Courses / Curriculum
    continuingEducation: 'CONTINUING EDUCATION',
    myCurriculum: 'MY CURRICULUM',
    activeCoursesLabel: 'ACTIVE COURSES',
    completionRateLabel: 'COMPLETION RATE',
    searchBtn: 'SEARCH',

    // All Courses Catalog
    curatedCatalog: 'CURATED CATALOG',
    ourCoursesTitle: 'OUR COURSES',
    availableStat: 'AVAILABLE',
    newTodayStat: 'NEW TODAY',
    allCoursesTab: 'ALL COURSES',
    gsCoursesTab: 'GS COURSES',
    optionalCoursesTab: 'OPTIONAL COURSES',
    testSeriesTab: 'TEST SERIES',
    buyBooksTab: 'BUY BOOKS',
    businessTab: 'BUSINESS',
    digitalMarketingTab: 'DIGITAL MARKETING',
    showingCoursesLabel: 'SHOWING COURSES',
    advancedFiltersBtn: 'ADVANCED FILTERS',

    // Forum
    totalTopicsLabel: 'TOTAL TOPICS',
    activeUsersLabel: 'ACTIVE USERS',
    thisWeekLabel: 'THIS WEEK',
    recentDiscourse: 'RECENT DISCOURSE',
    filterByIntelligence: 'FILTER BY INTELLIGENCE',

    // Job Posts
    manageJobOpps: 'MANAGE AND TRACK YOUR PUBLISHED JOB OPPORTUNITIES',
    createNewPost: 'CREATE NEW POST',
    totalPostsLabel: 'TOTAL POSTS',
    activeLeadsLabel: 'ACTIVE LEADS',
    totalProposalsLabel: 'TOTAL PROPOSALS',
    myPublications: 'MY PUBLICATIONS',

    // Floating Navbar Popups
    recentDispatches: 'RECENT DISPATCHES',
    markAllRead: 'MARK ALL READ',
    viewAllAlerts: 'VIEW ALL ALERTS',
    protocolXPAcquired: 'Protocol XP Acquired',
    xpDesc: '+250 for Color Theory Basic',
    moduleUploaded: 'Module Uploaded',
    moduleUploadedDesc: 'New content in Cinematography',
    communitySignal: 'Community Signal',
    communitySignalDesc: 'Marcus R. replied to your thread',
    rankCarrier: 'RANK CARRIER',
    identityProfile: 'IDENTITY PROFILE',
    systemSettings: 'SYSTEM SETTINGS',
    accessKeys: 'ACCESS KEYS',

    // Support Screen
    supportCenter: 'SUPPORT CENTER',
    activeDispatches: 'ACTIVE DISPATCHES',
    raiseTicket: 'RAISE A TICKET',
    myTickets: 'MY TICKETS',
    contactInfo: 'CONTACT INFORMATION',
    supportCategory: 'SUPPORT CATEGORY',
    intelligenceBriefing: 'INTELLIGENCE BRIEFING',
    attachments: 'ATTACHMENTS',
    submitDispatch: 'SUBMIT DISPATCH',
    raisedTickets: 'RAISED TICKETS',

    supportProtocolTag: 'SUPPORT PROTOCOL V2.1',
    infoArchitectureTag: 'INFORMATION ARCHITECTURE',
    strategicClassificationTag: 'STRATEGIC CLASSIFICATION',
    detailedDossierTag: 'DETAILED DOSSIER',
    intelligenceBriefingTitle: 'INTELLIGENCE BRIEFING',
    describeSituationPlaceholder: 'DESCRIBE YOUR SITUATION IN DETAIL...',
    supportingAssetsTag: 'SUPPORTING ASSETS',
    attachmentsTitle: 'ATTACHMENTS',
    submitAssetsLabel: 'SUBMIT ASSETS',
    fileTypesMax: 'JPG, PNG, PDF (MAX 10MB)',
    establishCommunication: 'ESTABLISH COMMUNICATION.',
    operativesResponseDesc: 'Our operatives typically respond within a 24-hour window. Discovery of the intersection of technology, design, and classical theory remains our primary protocol.',
    intelligenceLogTag: 'INTELLIGENCE LOG',
    protocolIdCol: 'PROTOCOL ID',
    briefingSubjectCol: 'BRIEFING SUBJECT',
    classificationCol: 'CLASSIFICATION',
    currentStateCol: 'CURRENT STATE',
    timestampCol: 'TIMESTAMP',
    retrievingDispatches: 'RETRIEVING DISPATCHES...',
    noDispatchesFound: 'No active dispatches found in archive.',

    // Contact Page
    getInTouch: 'GET IN TOUCH',
    contactUs: 'CONTACT US.',
    contactDesc: 'We are here to help! Whether you have questions about our courses, need technical support, or just want to share feedback, the Support Team is always ready to assist you.',
    sendMessage: 'SEND A MESSAGE',
    yourNameLabel: 'YOUR NAME',
    phoneCodeLabel: 'CODE',
    subjectLabel: 'SUBJECT',
    messageLabel: 'MESSAGE',
    enterYourName: 'Enter your name',
    enterYourEmail: 'Enter your email',
    enterYourPhone: 'Enter your phone number',
    tellUsHowHelp: 'Tell us how we can help you... (optional)',
    sendMessageBtn: 'SEND MESSAGE',
    emailSupport: 'Email Support',
    officeAddress: 'Office Address',
    feedbackSuggestions: 'Feedback & Suggestions',
    socialMedia: 'Social Media',

    // Auth & Modals
    confirmLogoutTitle: 'Confirm Logout?',
    confirmLogoutMessage: 'You are about to terminate your active session. You will be returned to the main portal shortly.',
    logOutNowBtn: 'LOG OUT NOW',
    welcomeBackTitle: 'Welcome back',
    loginSubtitle: 'ENTER YOUR CREDENTIALS TO ACCESS YOUR ACCOUNT.',
    continueWithGoogle: 'CONTINUE WITH GOOGLE',
    joinTheCircleTitle: 'Join the circle',
    signupSubtitle: 'COMMENCE YOUR PATH TO ENERGY ALIGNMENT.',
    joinWithGoogle: 'JOIN WITH GOOGLE',
    sendOtpBtn: 'SEND OTP',
    resendOtpBtn: 'RESEND OTP',
    sendingOtpBtn: 'SENDING...',
    enterOtpPlaceholder: 'Enter OTP',
    verifyBtn: 'VERIFY',
    verifyingBtn: 'VERIFYING...',
    verifiedBtn: 'VERIFIED',
    requestResetLink: 'Request a reset link',
    requestResetLinkDesc: 'Enter the email attached to your account. If it exists, we will send a link to reset the password.',
    sendResetLinkBtn: 'SEND RESET LINK',

    // Hero & Landing
    heroBadge: 'ASTROLOGY & VASTU CONSULTANCY',
    heroTitleLine1: 'ALIGN YOUR ENERGY FOR A',
    heroTitleLine2: 'PURPOSEFUL LIFE',
    heroDesc: 'Transform your life with Dr. Yogesh Sharma’s practical, logical, and doable remedies in Astrology, Vastu Shastra, and Numerology.',
    exploreCourses: 'EXPLORE SERVICES',
    getStarted: 'GET STARTED',
    activeLearners: 'Consulted Clients',
    activeStudents: 'Active Seekers',
    completionRate: 'Satisfaction Rate',
    topRating: 'Client Rating',
    averageRating: 'Average Rating',

    // Gigs & Jobs
    gigsTitle: 'Gigs',
    gigsSubtitle: 'Explore high-impact opportunities and industry projects',
    filterBy: 'FILTER BY',
    categoryDesignBranding: 'Design & Branding',
    categoryContentCopywriting: 'Content & Copywriting',
    categoryVideoAudio: 'Video & Audio',
    categoryMarketingGrowth: 'Marketing & Growth',
    categoryTechWebsite: 'Tech & Website',
    categorySalesClientwork: 'Sales & Client Work',
    jobRole: 'Role',
    jobLocation: 'Location',
    jobReportTo: 'Report to',
    jobWorkingDays: 'Working days',
    jobTimings: 'Timings',
    positionOverview: 'Position Overview',
    applyNow: 'APPLY NOW',
    postedText: 'Posted',
    noGigsFound: 'No gigs found in this category',

    // News & Dispatches
    archive2024: 'ARCHIVE 2024',
    latestTitle: 'Latest',
    dispatchesTitle: 'Dispatches',
    searchNewsPlaceholder: 'Search news by topic...',
    viewsText: 'VIEWS',
    likesText: 'LIKES',

    // Create Job Modal
    createJobPostTitle: 'Create Job Post',
    editJobPostTitle: 'Edit Job Post',
    createJobPostDesc: 'Fill out the details to post your job',
    editJobPostDesc: 'Update the details of your job',
    jobTitleLabel: 'Job Title *',
    jobTitlePlaceholder: 'Enter job title',
    jobDescriptionLabel: 'Job Description *',
    jobDescriptionPlaceholder: 'Describe the job requirements, responsibilities, and qualifications...',
    jobDetailsHeader: 'Job Details',
    experienceLevelLabel: 'Experience Level *',
    jobModeLabel: 'Job Mode *',
    locationTypeLabel: 'Location Type *',
    currencyLabel: 'Currency *',
    budgetDetailsHeader: 'Budget Details',
    budgetRangeHeader: 'Budget Range',
    minBudgetLabel: 'Minimum Budget *',
    maxBudgetLabel: 'Maximum Budget *',
    durationHeader: 'Duration',
    durationValueLabel: 'Duration Value *',
    durationUnitLabel: 'Duration Unit *',
    requiredSkillsHeader: 'Required Skills',
    addSkillBtn: 'Add Skill',
    addSkillPlaceholder: 'Add a skill',
    jobImageHeader: 'Job Image',
    thumbnailLabel: 'Thumbnail Image',
    chooseFileBtn: 'Choose File',
    noFileChosen: 'No file chosen',
    createJobBtn: 'Create Job',
    updateJobBtn: 'Update Job',
    creatingJob: 'Creating...',
    updatingJob: 'Updating...',

    // Landing Sections & Home Page
    growthTitle: 'ENERGY ALIGNMENT & LIFE HARMONY',
    growthDesc: 'Transform life obstacles into prosperity and inner peace with personalized Astro-Vastu guidance and continuous support.',
    growthHeadline: 'Align Your Energy & Destiny',
    growthSub: 'Practical astrology, Vastu Shastra consultations, and Vedic knowledge to remove negativity and unlock prosperity.',
    
    selectedForYou: 'CURATED FOR YOU',
    selectionTitle: 'The Guidance',
    selectionSub: 'A hand-picked collection of Astro-Vastu lessons and remedies built to help you overcome life struggles, career blocks, and planetary doshas.',
    exploreAll: 'EXPLORE ALL',

    // CTAs & Badges
    startModule: 'START THE MODULE',
    viewJob: 'VIEW DETAILS',
    learnMore: 'LEARN MORE',
    careerSpotlight: 'SPECIAL FOCUS',
    curatedModule: 'CURATED GUIDANCE',
    registerNow: 'BOOK CONSULTATION',
    newBadge: 'NEW',

    // Forum & Assessment CTAs
    startNewTopic: 'START NEW TOPIC',
    contributeCollective: 'Contribute to the community discussion',
    popularTags: 'POPULAR TOPICS',
    startAssessment: 'START KUNDLI ASSESSMENT',
    retakeProtocol: 'RETAKE ASSESSMENT',
    systemOverview: 'SYSTEM OVERVIEW',
    noNeuralData: 'No Chart Data Found',
    cognitiveNotCalibrated: 'Your astrological profile has not been calibrated. Complete the form to unlock personalized guidance.',
    intelligenceNetwork: 'Astro-Vastu Network',

    // Auth & Reset Password
    resetPasswordTitle: 'PASSWORD RESET',
    newPassword: 'NEW PASSWORD',
    confirmPassword: 'CONFIRM PASSWORD',
    token: 'TOKEN',
    orCreateAccount: 'OR CREATE ACCOUNT',
    orEmail: 'OR EMAIL',
    accessTier: 'ACCESS TIER',

    // Placeholders & Filter Tabs
    searchArchive: 'SEARCH ARCHIVE',
    inProgress: 'IN PROGRESS',
    wishlist: 'WISHLIST',
    enterFullIdentity: 'ENTER FULL NAME',
    emailCoordinates: 'EMAIL ADDRESS',
    communicationLine: 'PHONE NUMBER',
    briefingSubject: 'SUBJECT / QUERY',
    enterName: 'ENTER NAME',
    phoneNumber: 'PHONE NUMBER',

    // News & Dossier
    backToNews: 'BACK TO ALL ARTICLES',
    scrollToUnlock: 'SCROLL TO UNLOCK ARTICLES',
    endOfArchive: 'END OF ASTRO ARTICLES',
    prevDispatch: 'PREVIOUS ARTICLE',
    nextDispatch: 'NEXT ARTICLE',

    // Forum Stats & Details
    likes: 'LIKES',
    replies: 'REPLIES',
    postReply: 'POST A REPLY',
    forumStats: 'COMMUNITY STATS',
    popularDiscourse: 'POPULAR DISCUSSIONS',
    backToForum: 'BACK TO FORUM',

    // Catalog & Fallbacks
    failedToLoad: 'FAILED TO LOAD SERVICES',
    noCoursesAvailable: 'NO SERVICES AVAILABLE',
    berlin: 'GLOBAL',
    remotelyAvailable: 'ONLINE CONSULTATION AVAILABLE',

    // Checkout & Features
    protocolActive: 'CONSULTATION ACTIVE',
    selectCoupon: 'SELECT COUPON',
    sslSecured: 'SSL SECURED',
    instantActivation: 'INSTANT CONFIRMATION',
    live: 'LIVE',
    seePricing: 'SEE PRICING',

    howWeHelp: 'HOW WE HELP / EXPERTISE',
    designedToGrow: 'Logical Solutions for Real Life Problems',
    brandFeaturesSub: 'Practical, doable remedies without superstition or false promises.',
    focus01Title: 'Vedic Kundli Analysis',
    focus01Desc: 'Understand your planetary alignments (Graha Dasha), strengths, and karmic patterns with personalized birth chart readings.',
    focus02Title: 'Astro-Vastu Remedies',
    focus02Desc: 'Harmonize your living and working spaces. Simple, non-destructive Vastu corrections that clear energy blocks and invite abundance.',
    focus03Title: 'Career & Financial Growth',
    focus03Desc: 'Identify auspicious periods for career moves, business investments, and overcome financial stagnation with proven remedial insights.',
    focus04Title: 'Doable Daily Upay',
    focus04Desc: 'No complicated rituals or fear-mongering. Purely logical, positive habits and energetic alignments tailored to your horoscope.',

    faqTitle: 'FREQUENTLY ASKED QUESTIONS',
    faqSubtitle: 'Everything you need to know about our astrological consultations, Vastu audits, and remedial guidance.',
    
    comparisonTitle: 'HAPPY LIFE ASTRO VS TRADITIONAL SUPERSTITION',
    comparisonSubtitle: 'Discover why thousands trust Dr. Yogesh Sharma’s transparent, logic-backed astrological guidance.',
    edrillaAdvantage: 'The Happy Life Astro Approach',
    traditionalWay: 'Traditional Superstition',
    
    benefitsTitle: 'WHY CHOOSE HAPPY LIFE ASTRO',
    benefitsSub: 'Grounded in authentic Vedic wisdom, focused on practical outcomes and inner peace.',
    
    guaranteeTitle: 'AUTHENTIC & PRACTICAL GUIDANCE',
    guaranteeDesc: '100% transparent and logic-driven astrological consultations with practical, easy-to-implement everyday remedies.',
    
    solutionTitle: 'THE COMPLETE ASTRO-VASTU SOLUTION',
    solutionSub: 'From foundational Kundli insights to actionable remedies for home and career.',
    
    catalogTitle: 'CURATED ASTROLOGY & VASTU SERVICES',
    catalogSub: 'Handcrafted learning modules and consultation packages tailored for personal and financial growth.',
    
    masterclassTitle: 'EXPERT MASTERCLASSES & WEBINARS',
    masterclassSub: 'Exclusive live sessions led by Dr. Yogesh Sharma on Vedic remedies and Vastu principles.',

    // Footer
    sloganMagic: "We don't do",
    sloganMagicBold: "BLACK MAGIC",
    sloganGuarantee: "No overnight results",
    sloganGuaranteeBold: "GUARANTEE",
    ambitionExecution: "Align Your Energy, Unlock Success, and Live with Purpose",
    privacyPolicy: "Privacy Policy",
    services: "Services",
    blog: "Blog",
    work: "Consultation",
    contact: "Contact",

    // Dashboard Components & Sidebar
    systemActive: "System Active",
    welcomeHello: "Hello",
    onTrack: "You are currently on track. Accelerate your learning by continuing your latest module.",
    currentXP: "Current XP",
    carrierLevel: "Carrier Level",
    weeklyGoals: "Weekly Goals",
    weeklyGoalsTitle: "Weekly Study Goals",
    weeklyGoalsSub: "Keep your streak alive by completing target hours every week.",
    focusConsistency: "Focusing on Consistency",
    enrolledCourses: "Enrolled Courses",
    completed: "Completed",
    completedModules: "Completed Modules",
    certificatesEarned: "Certificates Earned",
    totalXP: "Total XP Points",
    activeCoursesCount: "Active Courses",
    editGoals: "Edit Goals",
    continueLearning: "Continue Learning",
    progress: "Progress",
    resume: "Resume",
    topLearners: "Top Learners",
    upcomingDeadlines: "Upcoming Deadlines",
    recentActivity: "Recent Activity",
    recentActivityTitle: "Recent Activity Log",
    viewAllActivity: "View All Activity",
    auditTrail: "Audit Trail",
    noPendingAssignments: "No pending assignments",
    submissionRequired: "Submission Required",
    pending: "PENDING",

    // Authentication & Profile
    welcomeBack: "Welcome Back",
    signInAccount: "Sign in to your account",
    signupTitle: "Create Your Account",
    signupSub: "Start your journey today with full access to our learning platform.",
    createAccount: "Create Your Account",
    emailAddress: "Email Address",
    password: "Password",
    rememberMe: "Remember me",
    forgotPassword: "Forgot password?",
    donthaveAccount: "Don't have an account?",
    alreadyHaveAccount: "Already have an account?",
    signUpNow: "Sign up now",
    fullName: "Full Name",
    sendResetLink: "Send Reset Link",
    profileTitle: "User Profile Settings",
    profileSub: "Manage your personal information, security preferences, and connected accounts.",
    editProfile: "Edit Profile",
    saveChanges: "Save Changes",
    purchasesTitle: "My Purchases & Invoices",
    purchasesSub: "View all your past course enrollments, transaction receipts, and payment history.",
    myCoursesTitle: "My Enrolled Courses",
    myCoursesSub: "Track your course progress, resume modules, and access learning certificates.",
    liveClassesTitle: "Live Interactive Classes",
    joinClass: "JOIN LIVE SESSION",
    supportTitle: "Help & Support Center",
    supportSub: "Have questions or need assistance? Reach out to our dedicated support team 24/7.",

    // Course & Page UI
    allCoursesTitle: "EXPLORE ALL COURSES",
    searchCoursesPlaceholder: "Search by course title, skill, or instructor...",
    categoryAll: "All Categories",
    categoryWeb: "Web Development",
    categoryAI: "AI & Machine Learning",
    categoryDesign: "UI/UX Design",
    categoryData: "Data Science",
    enrollNow: "ENROLL NOW",
    viewDetails: "VIEW DETAILS",
    rating: "Rating",
    studentsEnrolled: "Students",
    forumTitle: "COMMUNITY DISCUSSIONS",
    forumSubtitle: "Ask questions, share insights, and connect with fellow developers.",
    gigTitle: "JOB & FREELANCE OPPORTUNITIES",
    gigSubtitle: "Discover hand-picked gigs and full-time tech roles tailored for your skill set.",
    newsTitle: "TECH INSIGHTS & UPDATES",
    newsSubtitle: "Stay updated with the latest trends in tech, design, and career growth.",
    contactTitle: "Get in Touch with Us",
    contactSub: "We would love to hear from you. Send us a message and we will respond as soon as possible.",
  },
  hi: {
    // Navigation & General
    home: 'मुख्य पृष्ठ',
    ourCourses: 'हमारे कोर्स',
    freeContent: 'मुफ्त सामग्री (Free Content)',
    freePdfs: 'पीडीएफ और नोट्स (PDFs)',
    freeClasses: 'क्लास और लेक्चर्स (Classes)',
    freeTests: 'टेस्ट और क्विज़ (Tests)',
    exploreFreeContent: 'सभी मुफ्त सामग्री देखें',
    forum: 'मंच (फोरम)',
    gig: 'गिग (नौकरियां)',
    news: 'समाचार',
    dashboard: 'डैशबोर्ड',
    signIn: 'साइन इन',
    logOut: 'लॉग आउट',
    liveClasses: 'लाइव कक्षाएं',
    profile: 'प्रोफ़ाइल',
    myActivity: 'मेरी गतिविधि',
    myForum: 'मेरा मंच',
    mySubmissions: 'मेरे सबमिशन',
    myPurchases: 'मेरी खरीदारी',
    myCourses: 'मेरे कोर्स',
    allCourses: 'सभी कोर्स',
    gsCourses: 'जीएस कोर्सेस',
    optionalCourses: 'वैकल्पिक कोर्सेस',
    testSeries: 'टेस्ट सीरीज़',
    buyBooks: 'पुस्तकें खरीदें',
    jobPostings: 'जॉब पोस्टिंग',
    support: 'सहायता और सहायता केंद्र',

    // Profile & User Info
    security: 'सुरक्षा',
    academic: 'शैक्षणिक',
    profileDetails: 'प्रोफ़ाइल विवरण',
    fullNameLabel: 'पूरा नाम',
    emailAddressLabel: 'ईमेल पता',
    phoneNumberLabel: 'फ़ोन नंबर',
    locationLabel: 'स्थान',
    aboutMeBio: 'मेरे बारे में / बायो',
    companyNameLabel: 'कंपनी का नाम',
    gstNumberLabel: 'जीएसटी नंबर',
    saveChangesBtn: 'परिवर्तन सहेजें',
    savingState: 'सहेज रहा है...',
    changesSavedMsg: 'परिवर्तन सहेजे गए',
    currentPasswordLabel: 'वर्तमान पासवर्ड',
    newPasswordLabel: 'नया पासवर्ड',
    confirmPasswordLabel: 'पासवर्ड की पुष्टि करें',
    updatePasswordBtn: 'पासवर्ड अपडेट करें',
    cancelBtn: 'रद्द करें',
    studentRole: 'छात्र',
    memberRole: 'सदस्य',
    coursesStat: 'कोर्स',
    postsStat: 'पोस्ट',
    certificatesStat: 'प्रमाणपत्र',
    personalityArchetype: 'व्यक्तित्व का प्रकार',
    coreDescription: 'मुख्य विवरण',
    bioSummary: 'बायो सारांश',
    noBioRecorded: 'रजिस्ट्री में कोई बायो दर्ज नहीं है।',
    badgesTitle: 'बैज',
    earlyAdopter: 'प्रारंभिक उपयोगकर्ता',
    verifiedUser: 'सत्यापित उपयोगकर्ता',
    accountInfo: 'खाता जानकारी',
    lockedLabel: 'लॉक',

    // Live Classes
    liveSignal: 'लाइव सिग्नल',
    noClassesActive: 'वर्तमान में कोई कक्षाएं सक्रिय नहीं हैं।',
    meetingDisconnected: 'मीटिंग डिस्कनेक्ट हो गई',
    disconnectedDesc: 'आप इस सत्र से हट गए हैं या डिस्कनेक्ट हो गए हैं।',
    reconnecting: 'पुनः कनेक्ट हो रहा है...',
    rejoin: 'पुनः जुड़ें',
    dismiss: 'खारिज करें',
    secureBroadcast: 'सुरक्षित प्रसारण',
    allScheduledClasses: 'सभी निर्धारित कक्षाएं',

    // Academic & Education
    educationHistory: 'शिक्षा का इतिहास',
    viewAll: 'सभी देखें',
    noHistoryRecorded: 'कोई इतिहास दर्ज नहीं है',
    addEducationDetails: 'अपनी शिक्षा का विवरण जोड़ें',
    addEducation: 'शिक्षा जोड़ें',
    myDocuments: 'मेरे दस्तावेज़',
    uploadFile: 'फ़ाइल अपलोड करें',

    // My Forum / Discourse
    myDiscourse: 'मेरी चर्चाएँ',
    discourseSub: 'आपके सामुदायिक योगदान और विषयों का संग्रह',
    totalThreads: 'कुल थ्रेड्स',
    engagement: 'सहभागिता',
    calibrations: 'कैलिब्रेशंस',
    noContributionsFound: 'कोई योगदान नहीं मिला',
    noThreadsStarted: 'आपने अभी तक कोई फ़ोरम थ्रेड शुरू नहीं किया है',

    // Submissions
    assignmentArchive: 'असाइनमेंट संग्रह',
    submissionsSub: 'अपने रणनीतिक सबमिशन और प्रदर्शन मेट्रिक्स को ट्रैक करें',
    performance: 'प्रदर्शन',

    // Purchases & Ledger
    archiveLedger: 'संग्रह और बहीखाता',
    purchasesLedgerSub: 'हैप्पी लाइफ पर आपके कोर्स नामांकन, परामर्श पैकेज और रसीदों का स्थायी रिकॉर्ड।',
    moduleArchive: 'मॉड्यूल संग्रह',
    acquisition: 'अधिग्रहण तिथि',
    amount: 'राशि',
    actions: 'कार्रवाई',
    receipt: 'रसीद',
    refund: 'रिफंड',

    // Messages
    messagesTitle: 'संदेश',
    activeChats: 'सक्रिय चैट:',
    chatsTab: 'चैट',
    groupsTab: 'समूह',
    searchMessages: 'संदेश खोजें...',
    allFilter: 'सभी',
    unreadFilter: 'अपठित',
    loadingChats: 'चैट लोड हो रही है...',
    connectionError: 'कनेक्शन त्रुटि',
    retryBtn: 'पुनः प्रयास करें',
    reconnectBtn: 'पुनः कनेक्ट करें',
    noMessagesFound: 'कोई संदेश नहीं मिला',
    participants: 'प्रतिभागी',
    searchParticipants: 'प्रतिभागियों की खोज करें...',
    clearChat: 'चैट साफ करें',
    selectConversation: 'मैसेजिंग शुरू करने के लिए कोई बातचीत चुनें',
    messagesSecure: 'आपके संदेश सुरक्षित हैं',
    typeMessage: 'एक संदेश टाइप करें...',

    // My Courses / Curriculum
    continuingEducation: 'सतत शिक्षा',
    myCurriculum: 'मेरा पाठ्यक्रम',
    activeCoursesLabel: 'सक्रिय पाठ्यक्रम',
    completionRateLabel: 'पूर्णता दर',
    searchBtn: 'खोजें',

    // All Courses Catalog
    curatedCatalog: 'क्यूरेटेड कैटलॉग',
    ourCoursesTitle: 'हमारे पाठ्यक्रम',
    availableStat: 'उपलब्ध',
    newTodayStat: 'आज नया',
    allCoursesTab: 'सभी पाठ्यक्रम',
    gsCoursesTab: 'जीएस पाठ्यक्रम',
    optionalCoursesTab: 'वैकल्पिक पाठ्यक्रम',
    testSeriesTab: 'टेस्ट सीरीज़',
    buyBooksTab: 'पुस्तकें खरीदें',
    businessTab: 'व्यवसाय',
    digitalMarketingTab: 'डिजिटल मार्केटिंग',
    showingCoursesLabel: 'पाठ्यक्रम दिखाए जा रहे हैं',
    advancedFiltersBtn: 'उन्नत फ़िल्टर',

    // Forum
    totalTopicsLabel: 'कुल विषय',
    activeUsersLabel: 'सक्रिय उपयोगकर्ता',
    thisWeekLabel: 'इस सप्ताह',
    recentDiscourse: 'हाल की चर्चा',
    filterByIntelligence: 'इंटेलिजेंस द्वारा फ़िल्टर करें',

    // Job Posts
    manageJobOpps: 'अपने प्रकाशित नौकरी के अवसरों को प्रबंधित और ट्रैक करें',
    createNewPost: 'नई पोस्ट बनाएं',
    totalPostsLabel: 'कुल पोस्ट',
    activeLeadsLabel: 'सक्रिय लीड्स',
    totalProposalsLabel: 'कुल प्रस्ताव',
    myPublications: 'मेरे प्रकाशन',

    // Floating Navbar Popups
    recentDispatches: 'हाल के संदेश',
    markAllRead: 'सभी को पढ़ा हुआ चिह्नित करें',
    viewAllAlerts: 'सभी अलर्ट देखें',
    protocolXPAcquired: 'प्रोटोकॉल एक्सपी प्राप्त किया',
    xpDesc: 'कलर थ्योरी बेसिक के लिए +250',
    moduleUploaded: 'मॉड्यूल अपलोड किया गया',
    moduleUploadedDesc: 'सिनेमैटोग्राफी में नई सामग्री',
    communitySignal: 'कम्युनिटी सिग्नल',
    communitySignalDesc: 'मार्कस आर. ने आपके थ्रेड का जवाब दिया',
    rankCarrier: 'रैंक कैरियर',
    identityProfile: 'पहचान प्रोफ़ाइल',
    systemSettings: 'सिस्टम सेटिंग्स',
    accessKeys: 'एक्सेस कुंजियाँ',

    // Support Screen
    supportCenter: 'सहायता केंद्र',
    activeDispatches: 'सक्रिय प्रेषण',
    raiseTicket: 'टिकट उठाएं',
    myTickets: 'मेरे टिकट',
    contactInfo: 'संपर्क जानकारी',
    supportCategory: 'सहायता श्रेणी',
    intelligenceBriefing: 'इंटेलीजेंस ब्रीफिंग',
    attachments: 'संलग्नक',
    submitDispatch: 'प्रेषण जमा करें',
    raisedTickets: 'उठाए गए टिकट',

    supportProtocolTag: 'सहायता प्रोटोकॉल V2.1',
    infoArchitectureTag: 'सूचना वास्तुकला',
    strategicClassificationTag: 'रणनीतिक वर्गीकरण',
    detailedDossierTag: 'विस्तृत डोजियर',
    intelligenceBriefingTitle: 'इंटेलीजेंस ब्रीफिंग',
    describeSituationPlaceholder: 'अपनी स्थिति का विस्तार से वर्णन करें...',
    supportingAssetsTag: 'सहायक संपत्ति',
    attachmentsTitle: 'संलग्नक',
    submitAssetsLabel: 'संपत्ति जमा करें',
    fileTypesMax: 'JPG, PNG, PDF (अधिकतम 10MB)',
    establishCommunication: 'संचार स्थापित करें।',
    operativesResponseDesc: 'हमारे प्रतिनिधि आमतौर पर 24 घंटे की अवधि के भीतर जवाब देते हैं। प्रौद्योगिकी, डिजाइन और शास्त्रीय सिद्धांत के प्रतिच्छेदन की खोज हमारा प्राथमिक प्रोटोकॉल है।',
    intelligenceLogTag: 'इंटेलीजेंस लॉग',
    protocolIdCol: 'प्रोटोकॉल आईडी',
    briefingSubjectCol: 'ब्रीफिंग विषय',
    classificationCol: 'वर्गीकरण',
    currentStateCol: 'वर्तमान स्थिति',
    timestampCol: 'समय',
    retrievingDispatches: 'प्रेषण प्राप्त किया जा रहा है...',
    noDispatchesFound: 'संग्रह में कोई सक्रिय प्रेषण नहीं मिला।',

    // Contact Page
    getInTouch: 'संपर्क करें',
    contactUs: 'हमसे संपर्क करें।',
    contactDesc: 'हम यहाँ आपकी मदद के लिए हैं! चाहे आपके पास हमारे पाठ्यक्रमों के बारे में प्रश्न हों, तकनीकी सहायता की आवश्यकता हो, या प्रतिक्रिया साझा करना चाहते हों, सहायता टीम हमेशा आपकी सहायता के लिए तैयार है।',
    sendMessage: 'एक संदेश भेजें',
    yourNameLabel: 'आपका नाम',
    phoneCodeLabel: 'कोड',
    subjectLabel: 'विषय',
    messageLabel: 'संदेश',
    enterYourName: 'अपना नाम दर्ज करें',
    enterYourEmail: 'अपना ईमेल दर्ज करें',
    enterYourPhone: 'अपना फ़ोन नंबर दर्ज करें',
    tellUsHowHelp: 'बताएं कि हम आपकी क्या मदद कर सकते हैं... (वैकल्पिक)',
    sendMessageBtn: 'संदेश भेजें',
    emailSupport: 'ईमेल सहायता',
    officeAddress: 'कार्यालय का पता',
    feedbackSuggestions: 'प्रतिक्रिया और सुझाव',
    socialMedia: 'सोशल मीडिया',

    // Auth & Modals
    confirmLogoutTitle: 'लॉगआउट की पुष्टि करें?',
    confirmLogoutMessage: 'आप अपना सक्रिय सत्र समाप्त करने वाले हैं। आपको जल्द ही मुख्य पोर्टल पर वापस भेज दिया जाएगा।',
    logOutNowBtn: 'अभी लॉगआउट करें',
    welcomeBackTitle: 'वापसी पर स्वागत है',
    loginSubtitle: 'अपने खाते में प्रवेश करने के लिए विवरण दर्ज करें।',
    continueWithGoogle: 'गूगल के साथ आगे बढ़ें',
    joinTheCircleTitle: 'समुदाय से जुड़ें',
    signupSubtitle: 'सुख, शांति और समृद्धि की अपनी यात्रा शुरू करें।',
    joinWithGoogle: 'गूगल के साथ जुड़ें',
    sendOtpBtn: 'ओटीपी भेजें',
    resendOtpBtn: 'पुनः ओटीपी भेजें',
    sendingOtpBtn: 'भेजा जा रहा है...',
    enterOtpPlaceholder: 'ओटीपी दर्ज करें',
    verifyBtn: 'सत्यापित करें',
    verifyingBtn: 'सत्यापित किया जा रहा है...',
    verifiedBtn: 'सत्यापित',
    requestResetLink: 'रीसेट लिंक का अनुरोध करें',
    requestResetLinkDesc: 'अपने खाते से जुड़ा ईमेल दर्ज करें। यदि यह मौजूद है, तो हम पासवर्ड रीसेट करने का लिंक भेजेंगे।',
    sendResetLinkBtn: 'रीसेट लिंक भेजें',

    // Hero & Landing
    heroBadge: 'ज्योतिष एवं वास्तु परामर्श',
    heroTitleLine1: 'सुख, शांति और समृद्धि के लिए',
    heroTitleLine2: 'सटीक वैदिक ज्योतिष और वास्तु',
    heroDesc: 'डॉ. योगेश शर्मा के साथ सरल, व्यावहारिक और प्रभावी ज्योतिष एवं वास्तु उपायों से अपने जीवन को संवारें।',
    exploreCourses: 'सेवाएं देखें',
    getStarted: 'शुरू करें',
    activeLearners: 'परामर्श प्राप्त ग्राहक',
    activeStudents: 'सक्रिय सदस्य',
    completionRate: 'संतुष्टि दर',
    topRating: 'ग्राहक रेटिंग',
    averageRating: 'औसत रेटिंग',

    // Gigs & Jobs
    gigsTitle: 'सेवाएं',
    gigsSubtitle: 'व्यक्तिगत ज्योतिष एवं वास्तु परामर्श सेवाएं',
    filterBy: 'फ़िल्टर करें',
    categoryDesignBranding: 'कुंडली विश्लेषण',
    categoryContentCopywriting: 'वास्तु परामर्श',
    categoryVideoAudio: 'अंकशास्त्र (न्यूमरोलॉजी)',
    categoryMarketingGrowth: 'ग्रह शांति उपाय',
    categoryTechWebsite: 'करियर मार्गदर्शन',
    categorySalesClientwork: 'विवाह एवं संबंध',
    jobRole: 'भूमिका',
    jobLocation: 'स्थान',
    jobReportTo: 'रिपोर्टिंग',
    jobWorkingDays: 'कार्य दिवस',
    jobTimings: 'समय',
    positionOverview: 'विवरण',
    applyNow: 'परामर्श बुक करें',
    postedText: 'पोस्ट किया गया',
    noGigsFound: 'इस श्रेणी में कोई विवरण नहीं मिला',

    // News & Dispatches
    archive2024: 'संग्रह 2024',
    latestTitle: 'नवीनतम',
    dispatchesTitle: 'ज्योतिष लेख',
    searchNewsPlaceholder: 'विषय के अनुसार लेख खोजें...',
    viewsText: 'दृश्य',
    likesText: 'पसंद',

    // Create Job Modal
    createJobPostTitle: 'परामर्श अनुरोध बनाएं',
    editJobPostTitle: 'अनुरोध संपादित करें',
    createJobPostDesc: 'परामर्श के लिए अपना विवरण भरें',
    editJobPostDesc: 'अपना विवरण अपडेट करें',
    jobTitleLabel: 'शीर्षक *',
    jobTitlePlaceholder: 'शीर्षक दर्ज करें',
    jobDescriptionLabel: 'समस्या का विवरण *',
    jobDescriptionPlaceholder: 'अपनी समस्या या प्रश्न का विवरण दर्ज करें...',
    jobDetailsHeader: 'परामर्श विवरण',
    experienceLevelLabel: 'प्राथमिकता स्तर *',
    jobModeLabel: 'माध्यम *',
    locationTypeLabel: 'परामर्श का प्रकार *',
    currencyLabel: 'मुद्रा *',
    budgetDetailsHeader: 'शुल्क विवरण',
    budgetRangeHeader: 'शुल्क सीमा',
    minBudgetLabel: 'न्यूनतम शुल्क *',
    maxBudgetLabel: 'अधिकतम शुल्क *',
    durationHeader: 'अवधि',
    durationValueLabel: 'अवधि का मान *',
    durationUnitLabel: 'अवधि की इकाई *',
    requiredSkillsHeader: 'संबंधित क्षेत्र',
    addSkillBtn: 'जोड़ें',
    addSkillPlaceholder: 'विषय जोड़ें',
    jobImageHeader: 'कुंडली / फोटो',
    thumbnailLabel: 'दस्तावेज़ छवि',
    chooseFileBtn: 'फ़ाइल चुनें',
    noFileChosen: 'कोई फ़ाइल नहीं चुनी गई',
    createJobBtn: 'अनुरोध भेजें',
    updateJobBtn: 'अनुरोध अपडेट करें',
    creatingJob: 'भेजा जा रहा है...',
    updatingJob: 'अपडेट किया जा रहा है...',

    // Landing Sections & Home Page
    growthTitle: 'ऊर्जा संतुलन और जीवन में सुख-समृद्धि',
    growthDesc: 'व्यक्तिगत ज्योतिष-वास्तु मार्गदर्शन और निरंतर समर्थन के साथ जीवन की बाधाओं को समृद्धि में बदलें।',
    growthHeadline: 'अपनी ऊर्जा और भाग्य को संवारें',
    growthSub: 'नकारात्मकता दूर करने और समृद्धि के द्वार खोलने के लिए व्यावहारिक ज्योतिष, वास्तु शास्त्र और वैदिक उपाय।',
    
    selectedForYou: 'आपके लिए विशेष',
    selectionTitle: 'विशेष मार्गदर्शन',
    selectionSub: 'जीवन की बाधाओं, करियर रुकावटों और ग्रह दोषों को दूर करने के लिए चुनिंदा ज्योतिष-वास्तु पाठ और उपाय।',
    exploreAll: 'सभी देखें',

    // CTAs & Badges
    startModule: 'मार्गदर्शन शुरू करें',
    viewJob: 'विवरण देखें',
    learnMore: 'अधिक जानें',
    careerSpotlight: 'विशेष फोकस',
    curatedModule: 'क्यूरेटेड मार्गदर्शन',
    registerNow: 'परामर्श बुक करें',
    newBadge: 'नया',

    // Forum & Assessment CTAs
    startNewTopic: 'नया विषय शुरू करें',
    contributeCollective: 'सामूहिक चर्चा में भाग लें',
    popularTags: 'लोकप्रिय विषय',
    startAssessment: 'कुंडली मूल्यांकन शुरू करें',
    retakeProtocol: 'पुनः मूल्यांकन लें',
    systemOverview: 'सिस्टम अवलोकन',
    noNeuralData: 'कोई डेटा नहीं मिला',
    cognitiveNotCalibrated: 'आपकी जन्म कुंडली का विश्लेषण अभी नहीं हुआ है। व्यक्तिगत परिणाम प्राप्त करने के लिए विवरण भरें।',
    intelligenceNetwork: 'एस्ट्रो-वास्तु नेटवर्क',

    // Auth & Reset Password
    resetPasswordTitle: 'पासवर्ड रीसेट',
    newPassword: 'नया पासवर्ड',
    confirmPassword: 'पासवर्ड की पुष्टि करें',
    token: 'टोकन',
    orCreateAccount: 'या खाता बनाएं',
    orEmail: 'या ईमेल करें',
    accessTier: 'एक्सेस स्तर',

    // Placeholders & Filter Tabs
    searchArchive: 'संग्रह खोजें',
    inProgress: 'प्रगति में',
    wishlist: 'इच्छासूची',
    enterFullIdentity: 'अपना पूरा नाम दर्ज करें',
    emailCoordinates: 'ईमेल आईडी दर्ज करें',
    communicationLine: 'फोन नंबर दर्ज करें',
    briefingSubject: 'विषय / प्रश्न दर्ज करें',
    enterName: 'नाम दर्ज करें',
    phoneNumber: 'फोन नंबर',

    // News & Dossier
    backToNews: 'सभी लेखों पर वापस जाएं',
    scrollToUnlock: 'लेख अनलॉक करने के लिए स्क्रॉल करें',
    endOfArchive: 'लेख संग्रह समाप्त',
    prevDispatch: 'पिछला लेख',
    nextDispatch: 'अगला लेख',

    // Forum Stats & Details
    likes: 'पसंद',
    replies: 'जवाब',
    postReply: 'उत्तर पोस्ट करें',
    forumStats: 'समुदाय आंकड़े',
    popularDiscourse: 'लोकप्रिय चर्चाएं',
    backToForum: 'मंच पर वापस जाएं',

    // Catalog & Fallbacks
    failedToLoad: 'सेवाएं लोड करने में विफल',
    noCoursesAvailable: 'कोई सेवा उपलब्ध नहीं है',
    berlin: 'वैश्विक',
    remotelyAvailable: 'ऑनलाइन परामर्श उपलब्ध',

    // Checkout & Features
    protocolActive: 'परामर्श सक्रिय',
    selectCoupon: 'कूपन चुनें',
    sslSecured: 'एसएसएल सुरक्षित',
    instantActivation: 'तत्काल पुष्टि',
    live: 'लाइव',
    seePricing: 'मूल्य निर्धारण देखें',

    howWeHelp: 'हम कैसे मदद करते हैं / विशेषज्ञता',
    designedToGrow: 'वास्तविक समस्याओं के लिए तार्किक और सरल समाधान',
    brandFeaturesSub: 'बिना किसी अंधविश्वास या झूठे वादों के व्यावहारिक और सरल उपाय।',
    focus01Title: 'वैदिक कुंडली विश्लेषण',
    focus01Desc: 'अपनी जन्म कुंडली के ग्रहों, दशाओं और कर्म पैटर्न को समझें और सही मार्गदर्शन प्राप्त करें।',
    focus02Title: 'वास्तु एवं ग्रह शांति उपाय',
    focus02Desc: 'अपने घर और कार्यस्थल की ऊर्जा को संतुलित करें। बिना तोड़-फोड़ के सरल वास्तु उपायों से समृद्धि पाएं।',
    focus03Title: 'करियर एवं आर्थिक उन्नति',
    focus03Desc: 'करियर और व्यवसाय के लिए शुभ समय पहचानें और आर्थिक बाधाओं को दूर करने के सटीक उपाय जानें।',
    focus04Title: 'सरल और व्यावहारिक उपाय',
    focus04Desc: 'कठिन अनुष्ठानों के बिना तार्किक, सकारात्मक और आपकी राशि के अनुकूल दैनिक उपाय।',

    faqTitle: 'अक्सर पूछे जाने वाले प्रश्न (FAQ)',
    faqSubtitle: 'हमारे ज्योतिष परामर्श, वास्तु विश्लेषण और मार्गदर्शन के बारे में सब कुछ जानें।',
    
    comparisonTitle: 'हैप्पी लाइफ एस्ट्रो बनाम पारंपरिक अंधविश्वास',
    comparisonSubtitle: 'जानिए क्यों हजारों लोग डॉ. योगेश शर्मा के तार्किक और पारदर्शी मार्गदर्शन पर भरोसा करते हैं।',
    edrillaAdvantage: 'हैप्पी लाइफ एस्ट्रो का दृष्टिकोण',
    traditionalWay: 'पारंपरिक अंधविश्वास',
    
    benefitsTitle: 'हैप्पी लाइफ एस्ट्रो क्यों चुनें',
    benefitsSub: 'प्रामाणिक वैदिक ज्ञान, वास्तविक परिणाम और मानसिक शांति पर आधारित।',
    
    guaranteeTitle: 'प्रामाणिक और व्यावहारिक मार्गदर्शन',
    guaranteeDesc: 'सरल और करने योग्य दैनिक उपायों के साथ 100% पारदर्शी और तार्किक ज्योतिषीय सलाह।',
    
    solutionTitle: 'संपूर्ण ज्योतिष एवं वास्तु समाधान',
    solutionSub: 'बुनियादी कुंडली ज्ञान से लेकर घर और करियर के लिए व्यावहारिक उपायों तक।',
    
    catalogTitle: 'क्यूरेटेड ज्योतिष एवं वास्तु सेवाएं',
    catalogSub: 'व्यक्तिगत और वित्तीय विकास के लिए तैयार किए गए विशेष शिक्षण और परामर्श मॉड्यूल।',
    
    masterclassTitle: 'विशेषज्ञ मास्टरक्लास एवं वेबिनार',
    masterclassSub: 'डॉ. योगेश शर्मा के नेतृत्व में वैदिक उपायों और वास्तु सिद्धांतों पर विशेष लाइव सत्र।',

    // Footer
    sloganMagic: "हम नहीं करते कोई",
    sloganMagicBold: "काला जादू",
    sloganGuarantee: "रातों-रात चमत्कार की झूठी",
    sloganGuaranteeBold: "गारंटी नहीं",
    ambitionExecution: "ऊर्जा को संतुलित करें, सफलता पाएं और उद्देश्यपूर्ण जीवन जिएं",
    privacyPolicy: "गोपनीयता नीति",
    services: "सेवाएं",
    blog: "ब्लॉग",
    work: "परामर्श",
    contact: "संपर्क करें",

    // Dashboard Components & Sidebar
    systemActive: "सिस्टम सक्रिय",
    welcomeHello: "नमस्ते",
    onTrack: "आप वर्तमान में सही मार्ग पर हैं। अपने नवीनतम मॉड्यूल को जारी रखकर अपनी सीख बढ़ाएं।",
    currentXP: "वर्तमान एक्सपी",
    carrierLevel: "कैरियर स्तर",
    weeklyGoals: "साप्ताहिक लक्ष्य",
    weeklyGoalsTitle: "साप्ताहिक अध्ययन लक्ष्य",
    weeklyGoalsSub: "हर हफ्ते लक्ष्य घंटे पूरे करके अपनी स्ट्रीक को जीवित रखें।",
    focusConsistency: "निरंतरता पर ध्यान",
    enrolledCourses: "नामांकित कोर्स",
    completed: "पूरा किया गया",
    completedModules: "पूरे किए गए मॉड्यूल",
    certificatesEarned: "प्राप्त प्रमाण पत्र",
    totalXP: "कुल एक्सपी अंक",
    activeCoursesCount: "सक्रिय कोर्स",
    editGoals: "लक्ष्य संपादित करें",
    continueLearning: "सीखना जारी रखें",
    progress: "प्रगति",
    resume: "दोबारा शुरू करें",
    topLearners: "शीर्ष शिक्षार्थी",
    upcomingDeadlines: "आगामी समय सीमा",
    recentActivity: "हाल की गतिविधि",
    recentActivityTitle: "हाल की गतिविधि लॉग",
    viewAllActivity: "सभी गतिविधि देखें",
    auditTrail: "ऑडिट ट्रेल",
    noPendingAssignments: "कोई असाइनमेंट लंबित नहीं है",
    submissionRequired: "सबमिशन आवश्यक",
    pending: "लंबित",

    // Authentication & Profile
    welcomeBack: "वापसी पर स्वागत है",
    signInAccount: "अपने खाते में साइन इन करें",
    signupTitle: "अपना खाता बनाएं",
    signupSub: "हमारे शिक्षण मंच तक पूर्ण पहुंच के साथ आज ही अपनी यात्रा शुरू करें।",
    createAccount: "अपना खाता बनाएं",
    emailAddress: "ईमेल पता",
    password: "पासवर्ड",
    rememberMe: "मुझे याद रखें",
    forgotPassword: "पासवर्ड भूल गए?",
    donthaveAccount: "खाता नहीं है?",
    alreadyHaveAccount: "क्या आपके पास पहले से एक खाता मौजूद है?",
    signUpNow: "अभी साइन अप करें",
    fullName: "पूरा नाम",
    sendResetLink: "रीसेट लिंक भेजें",
    profileTitle: "उपयोगकर्ता प्रोफ़ाइल सेटिंग्स",
    profileSub: "अपनी व्यक्तिगत जानकारी, सुरक्षा प्राथमिकताओं और कनेक्टेड खातों को प्रबंधित करें।",
    editProfile: "प्रोफ़ाइल संपादित करें",
    saveChanges: "परिवर्तन सहेजें",
    purchasesTitle: "मेरी खरीदारी और इनवॉइस",
    purchasesSub: "अपने पिछले सभी कोर्स नामांकन, लेनदेन रसीदें और भुगतान इतिहास देखें।",
    myCoursesTitle: "मेरे नामांकित कोर्स",
    myCoursesSub: "अपनी पाठ्यक्रम प्रगति को ट्रैक करें, मॉड्यूल फिर से शुरू करें और प्रमाणपत्र एक्सेस करें।",
    liveClassesTitle: "लाइव इंटरेक्टिव कक्षाएं",
    joinClass: "लाइव सत्र में शामिल हों",
    supportTitle: "सहायता और समर्थन केंद्र",
    supportSub: "प्रश्न हैं या सहायता की आवश्यकता है? हमारी समर्पित सहायता टीम से 24/7 संपर्क करें।",

    // Course & Page UI
    allCoursesTitle: "सभी कोर्स देखें",
    searchCoursesPlaceholder: "कोर्स शीर्षक, कौशल या प्रशिक्षक द्वारा खोजें...",
    categoryAll: "सभी श्रेणियां",
    categoryWeb: "वेब डेवलपमेंट",
    categoryAI: "एआई और मशीन लर्निंग",
    categoryDesign: "यूआई/यूएक्स डिजाइन",
    categoryData: "डेटा साइंस",
    enrollNow: "अभी नामांकित करें",
    viewDetails: "विवरण देखें",
    rating: "रेटिंग",
    studentsEnrolled: "छात्र",
    forumTitle: "समुदाय चर्चाएं",
    forumSubtitle: "प्रश्न पूछें, विचार साझा करें और साथी डेवलपर्स के साथ जुड़ें।",
    gigTitle: "नौकरी और फ्रीलांस अवसर",
    gigSubtitle: "अपने कौशल सेट के लिए तैयार किए गए हाथ से चुने गए गिग और पूर्णकालिक टेक भूमिकाओं की खोज करें।",
    newsTitle: "टेक अंतर्दृष्टि और अपडेट",
    newsSubtitle: "तकनीक, डिज़ाइन और करियर विकास के नवीनतम रुझानों से अपडेट रहें।",
    contactTitle: "हमसे संपर्क करें",
    contactSub: "हम आपसे सुनना पसंद करेंगे। हमें एक संदेश भेजें और हम जल्द से जल्द जवाब देंगे।",
  }
}

const LanguageContext = createContext({
  language: 'en',
  setLanguage: () => {},
  t: (key) => key,
})

export const LanguageProvider = ({ children }) => {
  const [language, setLanguageState] = useState(() => {
    try {
      return localStorage.getItem('app_language') || 'en'
    } catch (e) {
      return 'en'
    }
  })

  const setLanguage = (lang) => {
    setLanguageState(lang)
    try {
      localStorage.setItem('app_language', lang)
    } catch (e) {
      console.warn('Failed to save language in localStorage', e)
    }
  }

  const t = (key) => {
    return translations[language]?.[key] || translations['en']?.[key] || key
  }

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  )
}

export const useLanguage = () => useContext(LanguageContext)
export default LanguageContext
